agenda/urls.py
from django.urls import path, re_path

from . import views, views_public

urlpatterns = [
    # Public part
    path('rendez-vous/', views_public.AppointmentWizard.as_view(), name='agenda-public'),
    path('rendez-vous/<int:pk>/termine/', views_public.AppointmentDoneView.as_view(), name='agenda-public-termine'),
    path('rendez-vous/annuler/<signature>/', views_public.AppointmentCancelView.as_view(),
         name='agenda-public-annuler'),

    # Authenticated part
    path('', views.AgendaChoiceView.as_view(), name='agenda-choice'),
    re_path(r'^ipe/(?:(?P<year>[0-9]+)/(?P<week>[0-9]+)/)?$', views.IPEAgendasView.as_view(), name='agendas-ipe'),
    re_path(r'^centre/(?P<centre>[^/]+)/(?:(?P<year>[0-9]+)/(?P<week>[0-9]+)/)?$', views.CentreAgendaView.as_view(),
            name='agenda-centre'),
    path('jour/<int:year>/<int:month>/<int:day>/', views.DayAgendaView.as_view(), name='agenda-day'),
    path('<username>/add/<slug:typ>/', views.PersonAgendaEditView.as_view(), name='person-agenda-add'),
    path('<username>/<int:pk>/edit/', views.PersonAgendaEditView.as_view(), name='person-agenda-edit'),
    path('<username>/<int:pk>/delete/', views.PersonAgendaDeleteView.as_view(), name='person-agenda-delete'),
    path('<username>/<int:pk>/toggle/', views.PersonAgendaToggleOccurrence.as_view(), name='person-agenda-toggleocc'),
    path('centre/<centre_pk>/add/<slug:typ>/', views.CentreAgendaEditView.as_view(), name='centre-agenda-add'),
    # Must come late, otherwise optional year/week catched too early.
    re_path(r'^(?P<username>[^/]+)/(?:(?P<year>[0-9]+)/(?P<week>[0-9]+)/)?', views.PersonAgendaView.as_view(),
            name='person-agenda'),
]

amf/urls.py
from django.urls import path

from . import views, views_stats

urlpatterns = [
    # Famille
    path('famille/list/', views.FamilleListView.as_view(), name='amf-famille-list'),
    path('famille/suivis-termines/', views.FamilleListView.as_view(mode='termines'),
         name='amf-famille-suivis-termines'),
    path('famille/add/', views.FamilleCreateView.as_view(), name='amf-famille-add'),
    path('famille/<int:pk>/edit/', views.FamilleUpdateView.as_view(), name='amf-famille-edit'),
    path('famille/<int:pk>/suivi/', views.AMFSuiviView.as_view(), name='amf-famille-suivi'),

    # Journal
    path('famille/<int:pk>/prestation/list/', views.PrestationListView.as_view(), name='amf-journal-list'),
    path('famille/<int:pk>/prestation/add/', views.PrestationCreateView.as_view(), name='amf-prestation-famille-add'),
    path('famille/<int:pk>/prestation/<int:obj_pk>/edit/', views.PrestationUpdateView.as_view(),
         name='amf-prestation-edit'),
    path('famille/<int:pk>/prestation/<int:obj_pk>/delete/', views.PrestationDeleteView.as_view(),
         name='amf-prestation-delete'),

    path('formation/list/', views.FormationListView.as_view(), name="amf-formation-list"),
    path('formation/add/', views.FormationCreateView.as_view(), name="amf-formation-add"),
    path('formation/<int:pk>/edit/', views.FormationUpdateView.as_view(), name="amf-formation-edit"),
    path('formation/<int:pk>/inscription/', views.FormationInscriptionView.as_view(),
         name="amf-formation-inscription"),
    path('famille/<int:pk>/inscription/autocomplete/', views.ParticipantsFormationAutocomplete.as_view(),
         name='amf-inscription-autocomplete'),

    path('stats/familles/', views_stats.StatistiquesFamillesView.as_view(), name='amf-stats-familles'),

    path('importation-spaj/', views.ImportationSPAJView.as_view(), name='amf-importation'),
]

cipe/urls.py
from django.urls import path

from archive import views as archive_views
from croixrouge.views import FamilleAutoCompleteView

from . import views, views_stats

app_name = "cipe"
urlpatterns = [
    path('famille/cipe/dal/', FamilleAutoCompleteView.as_view(typ='cipe'), name="famille-autocomplete"),
    path('famille/cipe/can_sms/', views.FamilleHasSMSView.as_view(), name="famille-can-sms"),

    # Famille
    path('famille/list/', views.FamilleListView.as_view(), name='famille-list'),
    path('famille/add/', views.FamilleCreateView.as_view(), name='famille-add'),
    path('famille/<int:pk>/edit/', views.FamilleUpdateView.as_view(), name='famille-edit'),
    path('famille/<int:pk>/delete/', views.FamilleDeleteView.as_view(), name='famille-delete'),
    path('famille/<int:pk>/print-info/', views.CoordonneesPDFView.as_view(), name='print-coord-famille'),
    path('famille/suivis_archives/', views.SuivisArchivesView.as_view(), name='suivis-archives'),
    path('famille/<int:pk>/personne/add/', views.PersonneCreateView.as_view(), name="personne-add"),

    # Prestations
    path('famille/<int:pk>/prestation/list/', views.PrestationListView.as_view(),
         name='prestation-famille-list'),
    path('famille/<int:pk>/enfant/<int:pk_pers>/prestation/list/', views.PrestationListView.as_view(),
         name='prestation-enfant-list'),
    path('famille/<int:pk>/enfant/<int:pk_pers>/prestation/add/', views.PrestationCreateView.as_view(),
         name='prestation-enfant-add'),
    path('famille/<int:pk>/prestation/<int:obj_pk>/edit/', views.PrestationUpdateView.as_view(),
         name='prestation-edit'),
    path('famille/<int:pk>/prestation/<int:obj_pk>/delete/', views.PrestationDeleteView.as_view(),
         name='prestation-delete'),
    path('prestation/<int:obj_pk>/deletefile/', views.PrestationDeleteFile.as_view(),
         name='prestation-deletefile'),
    path('utilisateur/prestations/', views.PrestationUtilisateurListView.as_view(), {'unite': 'cipe'},
         name='prestations-utilisateur'),
    path('prestation_gen/add/', views.PrestationGenEditView.as_view(is_create=True),
         name='prestation-gen-add'),
    path('prestation_gen/<int:pk>/edit/', views.PrestationGenEditView.as_view(is_create=False),
         name='prestation-gen-edit'),
    path('prestation_gen/<int:pk>/delete/', views.PrestationGenDeleteView.as_view(),
         name='prestation-gen-delete'),

    path('famille/<int:pk>/enfant/<int:pk_pers>/perinatal/', views.EnfantPerinatalView.as_view(),
         name='enfant-perinatal'),
    path('lieuacc/auto/', views.LieuAccouchementAutocompleteView.as_view(), name='lieuacc-autocomplete'),
    path('famille/<int:pk>/enfant/<int:pk_pers>/psycho/', views.EnfantPsychoView.as_view(), name='enfant-psycho'),
    path('famille/<int:pk>/enfant/<int:pk_pers>/psychoedit/', views.EnfantPsychoEditView.as_view(),
         name='enfant-psychoedit'),
    path('famille/<int:pk>/psychoedit/<int:pk_item>/', views.EnfantPsychoEditView.as_view(),
         name='item-psychoedit'),

    # Percentile
    path('enfant/<int:pk>/percentile/poids/', views.PercentileView.as_view(), {'typ': 'poids'},
         name='enfant-percentile-poids'),
    path('enfant/<int:pk>/percentile/taille/', views.PercentileView.as_view(), {'typ': 'taille'},
         name='enfant-percentile-taille'),
    path('enfant/<int:pk>/print/percentile/poids/', views.PercentilePoidsPDFView.as_view(),
         name='print-percentile-poids'),
    path('enfant/<int:pk>/print/percentile/taille/', views.PercentileTaillePDFView.as_view(),
         name='print-percentile-taille'),
    path('enfant/<int:pk>/percentile/email/', views.PercentileByEmailView.as_view(),
         name='enfant-percentile-email'),
    path('enfant/<int:pk>/archiver/', archive_views.ArchiveCreateView.as_view(default_unite="cipe"),
         name='enfant-archiver'),
    path('archive/<int:pk>/desarchiver/', archive_views.ArchiveCIPEDecryptView.as_view(),
         name='enfant-desarchiver'),

    # Thèmes de santé
    path('themesante/list/', views.ThemeSanteListView.as_view(), name='themesante-list'),
    path('themesante/add/', views.ThemeSanteEditView.as_view(is_create=True), name='themesante-add'),
    path('themesante/<int:pk>/edit/', views.ThemeSanteEditView.as_view(), name='themesante-edit'),
    path('themedoc/list/', views.ThemeDocListView.as_view(), name='themedoc-list'),
    path('themedoc/add/', views.ThemeDocEditView.as_view(is_create=True), name='themedoc-add'),
    path('themedoc/<int:pk>/edit/', views.ThemeDocEditView.as_view(), name='themedoc-edit'),
    path('themedoc/<int:pk>/delete/', views.ThemeDocDeleteView.as_view(), name='themedoc-delete'),

    path('documents/', views.GeneralDocListView.as_view(), name='generaldoc-list'),
    path('documents/add/', views.GeneralDocEditView.as_view(is_create=True), name='generaldoc-add'),
    path('documents/<int:pk>/edit/', views.GeneralDocEditView.as_view(), name='generaldoc-edit'),
    path('documents/<int:pk>/delete/', views.GeneralDocDeleteView.as_view(), name='generaldoc-delete'),
    path('documents/categ/<int:pk>/edit/', views.GeneralDocCategEditView.as_view(), name='generaldoccateg-edit'),

    # Stats
    path('statistiques/familles/', views_stats.StatistiquesFamillesView.as_view(), name='stats-familles'),
    path('statistiques/interv/', views_stats.StatistiquesParIntervView.as_view(), name='stats-interv'),
    path('statistiques/localites/', views_stats.StatistiquesLocalitesView.as_view(), name='stats-localites'),
    path('statistiques/lieux/', views_stats.StatistiquesLieuxView.as_view(), name='stats-lieux'),
    path('statistiques/type/', views_stats.StatistiquesTypeView.as_view(), name='stats-type'),
    path('statistiques/nouvelles/', views_stats.StatistiquesNouvellesView.as_view(), name='stats-nouvelles'),
    path('statistiques/themes/', views_stats.StatistiquesThemesView.as_view(), name='stats-themes'),
    path('statistiques/nationalite/', views_stats.StatistiquesNationaliteView.as_view(),
         name='stats-nationalite'),
    path('statistiques/duree/', views_stats.StatistiquesDureeView.as_view(), name='stats-duree'),
    path('statistiques/gen/', views_stats.StatistiquesGenView.as_view(), name='stats-gen'),
    path('statistiques/export/', views_stats.StatistiquesExportView.as_view(), name='stats-export'),
    path('statistiques/export/santene/', views_stats.StatistiquesSanteNEView.as_view(),
         name='stats-export-santene'),
    path('statistiques/export/ascpe/', views_stats.StatistiquesASCPEView.as_view(), name='stats-export-ascpe'),
]

agenda/templates/agenda/agenda-public-annuler.html
{% extends 'agenda/agenda-public-base.html' %}

{% block subcontent %}
<form method="post" action=".">{% csrf_token %}
    <p>{{ cancel_msg }}</p>
    <div>
        <button type="submit">Oui, je le veux</button>
    </div>
</form>
{% endblock %}

agenda/templates/agenda/agenda-public-appointments.html
{% extends 'agenda/agenda-public-base.html' %}

{% block subcontent %}
<form id="reservation" class="reservation-form" method="post">{% csrf_token %}
    {% if message %}
        <div class="text-section">
            <p class="alert alert-info">{{ message }}</p>
        </div>
    {% endif %}

    {{ wizard.management_form }}
    {% if typ == 'tel' %}
        <p>Choisissez un rendez-vous possible pour une consultation par téléphone :</p>
    {% else %}
        <p>Choisissez un rendez-vous possible{% if form.location %} à «{{ form.location }}»{% endif %} :</p>
    {% endif %}
    {{ wizard.form.avail }}

    {% if wizard.steps.prev %}
        <button class="wizard_goto_step" name="wizard_goto_step" type="submit" value="{{ wizard.steps.prev }}">
            <img class="back_img" src="{% static 'img/back.svg' %}">{{ view.get_step_back_label }}
        </button>
    {% endif %}
</form>
{% endblock %}

agenda/templates/agenda/agenda-public-base.html
{% extends "base-public.html" %}

{% block title %}Consultations infirmières petite enfance{% endblock %}</title>

{% block extrastyle %}
    <meta name="description" content="Les consultations infirmières petite enfance sont à disposition des familles pour les accompagner durant les 4 premières années de vie de leur enfant.">
{% endblock %}

{% block extra_javascript %}
    <script src="{% static 'js/agenda_public.js' %}" defer></script>
{% endblock %}

{% block content %}
    <h2>Prendre rendez-vous pour une consultation infirmière petite enfance</h2>
    <div class="text-section" aria-live="polite">
        {% block subcontent %}
        {% endblock %}
    </div>
{% endblock %}

agenda/templates/agenda/agenda-public-contact.html
{% extends 'agenda/agenda-public-base.html' %}

{% block subcontent %}
<form id="reservation" class="reservation-form final-form" method="post" novalidate>{% csrf_token %}
    {{ wizard.management_form }}
    {% if typ == 'tel' %}
        <p>Rendez-vous le {{ form.avail.start|date:'l j F à H:i' }} pour une consultation par téléphone :</p>
    {% else %}
        <p>Rendez-vous le {{ form.avail.start|date:'l j F à H:i' }}{% if centre %} à «{{ centre.nom }}»{% endif %} :</p>
    {% endif %}
    
    <div id="contact-form-div">
        {{ wizard.form }}
    </div>

    <button type="submit">Enregistrer et prendre rendez-vous</button>

    <button class="wizard_goto_step" name="wizard_goto_step" type="submit" value="{{ wizard.steps.prev }}">
        <img class="back_img" src="{% static 'img/back.svg' %}">{{ view.get_step_back_label }}
    </button>
</form>
{% endblock %}

agenda/templates/agenda/agenda-public-dates.html
{% extends 'agenda/agenda-public-base.html' %}

{% block subcontent %}
<form id="reservation" class="reservation-form" method="post">{% csrf_token %}
    {{ wizard.management_form }}
    
    {% if not wizard.form.date_avail %}
        <p>Malheureusement, il n’y a plus de rendez-vous disponible au cours des 4 prochaines semaines à cet endroit.</p>
    {% else %}
        <p>{{ form.prompt_string }}</p>
        {{ wizard.form.date_avail }}
    {% endif %}

    {% if wizard.steps.prev %}
        <button class="wizard_goto_step" name="wizard_goto_step" type="submit" value="{{ wizard.steps.prev }}">
            <img class="back_img" src="{% static 'img/back.svg' %}">{{ view.get_step_back_label }}
        </button>
    {% endif %}

    {% if not wizard.form.date_avail and 'téléphone' not in form.prompt_string %}
        <button class="wizard_goto_step" name="wizard_goto_step" type="submit" value="day-tel">
            <img class="back_img" src="{% static 'img/back.svg' %}">Réserver une consultation téléphonique
        </button>
    {% endif %}
</form>
{% endblock %}

agenda/templates/agenda/agenda-public-location.html
{% extends 'agenda/agenda-public-base.html' %}

{% block subcontent %}
<form id="reservation" class="reservation-form" method="post">{% csrf_token %}
    {{ wizard.management_form }}
    <p>Choisissez un lieu :</p>
    {{ wizard.form.location }}

    <ul id="id_location-location" class="immediate-submit">
        <li><label for="id_location-location_none">
            <input type="radio" name="location-location" value="any" class="immediate-submit" id="id_location-location_none">
            Prochaines disponibilités partout dans le canton</label>
        </li>
    </ul>

    {% if wizard.steps.prev %}
        <button class="wizard_goto_step" name="wizard_goto_step" type="submit" value="{{ wizard.steps.prev }}">
            <img class="back_img" src="{% static 'img/back.svg' %}">{{ view.get_step_back_label }}
        </button>
    {% endif %}

</form>
{% endblock %}

agenda/templates/agenda/agenda-public-termine.html
{% extends "agenda/agenda-public-base.html" %}

{% block subcontent %}

<p>Votre inscription pour le <strong>{{ event.start|date:"l j F" }} à {{ event.start|date:"H:i" }}</strong> a bien été prise en compte.</p>

<p>Une confirmation à été envoyée au numéro de téléphone ou à l'adresse courriel indiqués dans l’inscription.</p>

<p>Si vous deviez annuler ou modifier l’heure de ce rendez-vous, merci de bien vouloir utiliser le lien envoyé dans le message de confirmation ou appeler le secrétariat de la Croix-Rouge neuchâteloise au numéro 032 886 88 60.</p>

{% endblock %}

agenda/templates/agenda/agenda-public-type.html
{% extends 'agenda/agenda-public-base.html' %}

{% block subcontent %}
<form id="reservation" class="reservation-form" method="post">{% csrf_token %}
    {{ wizard.management_form }}
    <p>Choisissez le type de consultation souhaité :</p>
    {{ wizard.form.type_app }}
</form>

<div class="smaller">
    <i>Voir aussi:
    <ul class="mt-0">
        <li><a href="https://croix-rouge-ne.ch/services/consultations-infirmieres-petite-enfance/#sommeil-consultations">Consultations et ateliers sur le sommeil du petit enfant</a></li>
        <li><a href="https://croix-rouge-ne.ch/services/consultations-infirmieres-petite-enfance/#parents-enfants">Consultations courtes sans rendez-vous</a>
        </li>
    </ul>
    </i>
</div>

{% endblock %}

agenda/templates/agenda/agenda-week.html
{% extends 'cipe/base_cipe.html' %}
{% load agenda l10n %}

{% block extrastyle %}
<link rel="stylesheet" type="text/css" href="{% static 'css/agenda.css' %}">
{% endblock %}

{% block extra_javascript %}
<script type="module" src="{% static 'js/agenda.js' %}"></script>
{{ form_media }}
{% endblock %}

{% block content %}

{% if filter_form %}
    <form id="agenda-filter-form" method="post">{% csrf_token %}
        <div class="">
            Journée du <input type="text" name="date" class="vDateField" size="10" data-url="{% url 'agenda-day' 0 0 0 %}">
        </div>
        {{ filter_form.as_p }}
    </form>
{% endif %}

{% if agendas|length > 1 %}
    <div class="mt-3 mb-3">
        Agendas de:<br>
        {% for agenda in agendas %}
            {% if not forloop.first %}, {% endif %}
            <a href="#{{ agenda.person.username }}">{{ agenda.person.nom_prenom }}</a>
        {% endfor %}
    </div>
{% endif %}

{% for agenda in agendas %}
    <a name="{{ agenda.person.username }}"></a>
    <h2>{{ agenda.title }}</h2>

    <div style="display: flex; align-items: center; text-align: center; margin-bottom: 5px;">
        <div style="flex-grow: 0;">
            <a class="btn btn-secondary" href="{{ agenda.prev_events }}" title="Semaine précédente">&lt;</a>
        </div>

        <div style="flex: auto;">
            {% if agenda.add_dispo_url %}<a id="add-dispo-btn" class="btn btn-info js-add" href="{{ agenda.add_dispo_url }}">Ajouter une dispo</a>{% endif %}
            {% if agenda.add_rzv_url %}<a id="add-rzv-btn" class="btn btn-info js-add" href="{{ agenda.add_rzv_url }}">Ajouter un rendez-vous</a>{% endif %}
        </div>

        {% block center-buttons %}
        {% endblock %}

        <!--div style="flex: auto;">
            <a href="{{ agenda.print_url }}" title="Format PDF"><img class="ficon" src="{% static 'ficons/pdf.svg' %}"></a>
        </div-->

        <div style="flex-grow: 0;">
            <a class="btn btn-secondary" href="{{ agenda.next_events }}" title="Semaine suivante">&gt;</a>
        </div>
    </div>

    {% block agenda_content %}
    {% if agenda.has_holidays %}
    <div class="agenda-grid holiday-grid">
        {% for day, events in agenda.week_events.items %}
        <div class="cell-holiday">{% if events.holiday %}{{ events.holiday }}{% endif %}</div>
        {% endfor %}
    </div>
    {% endif %}
    <div class="agenda-grid {{ agenda.classes|default:'week-grid' }}"
         data-numcols="{{ agenda.week_events|length }}" data-numrows="{{ day_divs|length|add:1 }}"
         style="grid-template-rows: repeat({{ day_divs|length|add:1 }}, 24px);">
    {% for day, events in agenda.week_events.items %}
        <div class="agenda-head">{{ day|date:'D j F' }}</div>
        {% for dv in day_divs %}
            {% with events|get_events:dv as quart_evts %}
            <div class="event-cell {{ dv|is_hour|yesno:"hour," }} {{ dv|is_meal|yesno:"meal,"}}"
                 data-day="{{ day|date:'c' }}" data-hour="{{ dv|date:'H:i' }}">
                {% for ev in quart_evts %}
                <span class="event-content {{ ev.cancelled|yesno:'cancelled,' }} {{ ev.category.name }}"
                      style="height: calc({% mult ev.spans 100 %}% + {% mult ev.spans 2 %}px);
                             min-height: calc({% mult ev.spans 100 %}% + {% mult ev.spans 2 %}px);
                             left: {{ ev.leftoffset|default:0 }};
                             {% if events.col_width %}width: {% if ev.category.name == 'dispo' %}{{ events.col_width|unlocalize }}%{% else %}calc({{ events.col_width|unlocalize }}% - 22px){% endif %};{% endif %}
                             background-color: {{ ev.bg_color }};
                             color: {{ ev.text_color }};"
                       {% if ev.category.name == 'dispo' %}data-location="{{ ev.centre_id }}"{% endif %}>
                    {{ ev|before_icons }}
                    {% if ev|can_edit:request.user %}
                        <a class="js-edit" href="{% url 'person-agenda-edit' ev.person.username ev.pk %}{% if ev.is_recurring %}?occ={{ ev.start.isoformat|urlencode }}{% endif %}">
                            <img class="icon floatright" src="{% static 'img/edit.svg' %}" title="Modifier">
                        </a>
                    {% endif %}
                    {% if ev.is_recurring %}
                        <img class="icon floatright repeat" src="{% static 'img/repeat.svg' %}"
                             title="Cet événement est récurrent">
                    {% endif %}
                    {{ ev.start|as_hour_min }} - {{ ev.end|as_hour_min }}
                    {% if show_infs and ev.person %} <span title="{{ ev.person }}">[{{ ev.person.initiales }}]</span>{% endif %}
                    {% if ev.centre_id %}- {{ ev.centre }} - {% endif %}
                    {{ ev|event_details }}
                </span>
                {% endfor %}
            </div>
            {% endwith %}
        {% endfor %}
    {% endfor %}
    </div>
    {% endblock %}
{% endfor %}
{% endblock %}

agenda/templates/agenda/person-agenda-add.html
<!-- Loaded in BS modal -->
<form class="agenda-edit" method="post" action="{{ request.path }}">{% csrf_token %}
    {% if occ_date %}<input name="occ_date" type="hidden" value="{{ occ_date|date:'c' }}">{% endif %}
    <div>{{ form.non_field_errors }}</div>
    <div style="display: flex;">
        {% with form.date as field %}
        <div class="me-2">
            <div class="formfield {{ field.css_classes }}">{{ field.errors }}{{ field.label_tag }}</div> {{ field }}
        </div>
        {% endwith %}
        {% with form.heure_de as field %}
        <div class="me-2">
            <div class="formfield {{ field.css_classes }}">{{ field.errors }}{{ field.label_tag }}</div> {{ field }}
        </div>
        {% endwith %}
        {% with form.heure_a as field %}
        <div class="me-2">
            <div class="formfield {{ field.css_classes }}">{{ field.errors }}{{ field.label_tag }}</div> {{ field }}
        </div>
        {% endwith %}
    </div>
    {% if form.centre %}
    <div>
        {% with form.centre as field %}
        <div class="me-2">
            <div class="formfield {{ field.css_classes }}">{{ field.errors }}{{ field.label_tag }}</div> {{ field }}
        </div>
        {% endwith %}
    </div>
    {% endif %}
    {% if form.dispo_tel %}
    <div>
        {% with form.dispo_tel as field %}
        <div class="me-2">
            <div class="formfield {{ field.css_classes }}">{{ field.errors }}{{ field }} {{ field.label_tag|strip_colon }}</div>
        </div>
        {% endwith %}
    </div>
    {% endif %}
    {% if form.person %}
    <div>
        {% with form.person as field %}
        <div class="me-2">
            <div class="formfield {{ field.css_classes }}">{{ field.errors }}{{ field.label_tag }}</div> {{ field }}
        </div>
        {% endwith %}
    </div>
    {% endif %}

    {% if form.famille %}
        {% with form.famille as field %}
        <div class="formfield {{ field.css_classes }}">{{ field.errors }}{{ field.label_tag }}</div> {{ field }}
        {% endwith %}
    {% endif %}

    {% with form.description as field %}
    <div class="formfield {{ field.css_classes }}">{{ field.errors }}{{ field.label_tag }}</div> {{ field }}
    {% endwith %}

    {% if form.repetition %}
    {{ form.instance.repetition }}
    <details{% if form.category.name == 'dispo' or form.instance.rule %} open{% endif %}>
        <summary><b>Répétition</b></summary>
        <div>
            {% with form.repetition as field %}
            <div class="me-1">
                <div class="formfield {{ field.css_classes }}">{{ field.errors }}</div> {{ field }}
            </div>
            {% endwith %}
            {% with form.repetition_fin as field %}
            <div>
                <div class="formfield {{ field.css_classes }}">{{ field.errors }}{{ field.label_tag }}</div> {{ field }}
            </div>
            {% endwith %}
        </div>
    </details>
    {% endif %}

    {% with form.sms_confirm as field %}
    <div id="sms_confirm_container" class="formfield {{ field.css_classes }}"
         data-smscheckurl="{% url 'cipe:famille-can-sms' %}" hidden>
        {{ field.errors }}{{ field }} {{ field.label_tag|strip_colon }}
    </div>
    {% endwith %}

    <div class="boutons mt-3">
        <!-- first button, also default when 'enter'ing -->
        {% if form.instance.pk %}
            {% if form.instance.rule %}
            <button class="btn btn-primary submit" type="submit" name="modify-all-btn" value="on">
                Modifier toutes les occurrences
            </button>
            <button class="btn btn-primary submit ms-1" type="submit" name="modify-occ-btn" value="on">
                Modifier cette occurrence uniquement
            </button>
            {% else %}
            <button class="btn btn-primary submit" type="submit">Modifier</button>
            {% endif %}
        {% else %}
        <button class="btn btn-primary submit" type="submit">Créer</button>
        {% endif %}
        <button type="button" class="btn btn-secondary ms-1 cancel" data-bs-dismiss="modal">Annuler</button>
    </div>
</form>

{% if object.pk %}
<div class="boutons mt-3">
    {% if can_delete %}
    <form class="inline" method="get" action="{% url 'person-agenda-delete' object.person.username object.pk %}">
        <button type="submit" id="delete" class="btn btn-danger delete">Supprimer</button>
    </form>
    {% endif %}
    {% if occ_date %}
    <form class="inline" method="post" action="{% url 'person-agenda-toggleocc' object.person.username object.pk %}">
        {% csrf_token %}
        <input name="occ_date" type="hidden" value="{{ occ_date|date:'c' }}">
        <button type="button" id="delete" class="btn btn-warning delete confirm"
            data-confirm="Voulez-vous vraiment {% if occ_obj %}restaurer{% else %}annuler{% endif %} cette occurrence ?">
                {% if occ_obj %}Restaurer{% else %}Annuler{% endif %} l’occurrence du {{ occ_date|date:'j F' }}
        </button>
    </form>
    {% endif %}
</div>
{% endif %}