amf/urls.py
from django.urls import path

from . import views, views_stats

urlpatterns = [
    # Famille
    path('famille/list/', views.FamilleListView.as_view(), name='amf-famille-list'),
    path('famille/suivis-termines/', views.FamilleListView.as_view(mode='termines'),
         name='amf-famille-suivis-termines'),
    path('famille/add/', views.FamilleCreateView.as_view(), name='amf-famille-add'),
    path('famille/<int:pk>/edit/', views.FamilleUpdateView.as_view(), name='amf-famille-edit'),
    path('famille/<int:pk>/suivi/', views.AMFSuiviView.as_view(), name='amf-famille-suivi'),

    # Journal
    path('famille/<int:pk>/prestation/list/', views.PrestationListView.as_view(), name='amf-journal-list'),
    path('famille/<int:pk>/prestation/add/', views.PrestationCreateView.as_view(), name='amf-prestation-famille-add'),
    path('famille/<int:pk>/prestation/<int:obj_pk>/edit/', views.PrestationUpdateView.as_view(),
         name='amf-prestation-edit'),
    path('famille/<int:pk>/prestation/<int:obj_pk>/delete/', views.PrestationDeleteView.as_view(),
         name='amf-prestation-delete'),

    path('formation/list/', views.FormationListView.as_view(), name="amf-formation-list"),
    path('formation/add/', views.FormationCreateView.as_view(), name="amf-formation-add"),
    path('formation/<int:pk>/edit/', views.FormationUpdateView.as_view(), name="amf-formation-edit"),
    path('formation/<int:pk>/inscription/', views.FormationInscriptionView.as_view(),
         name="amf-formation-inscription"),
    path('famille/<int:pk>/inscription/autocomplete/', views.ParticipantsFormationAutocomplete.as_view(),
         name='amf-inscription-autocomplete'),

    path('stats/familles/', views_stats.StatistiquesFamillesView.as_view(), name='amf-stats-familles'),

    path('importation-spaj/', views.ImportationSPAJView.as_view(), name='amf-importation'),
]

cipe/urls.py
from django.urls import path

from archive import views as archive_views
from croixrouge.views import FamilleAutoCompleteView

from . import views, views_stats

app_name = "cipe"
urlpatterns = [
    path('famille/cipe/dal/', FamilleAutoCompleteView.as_view(typ='cipe'), name="famille-autocomplete"),
    path('famille/cipe/can_sms/', views.FamilleHasSMSView.as_view(), name="famille-can-sms"),

    # Famille
    path('famille/list/', views.FamilleListView.as_view(), name='famille-list'),
    path('famille/add/', views.FamilleCreateView.as_view(), name='famille-add'),
    path('famille/<int:pk>/edit/', views.FamilleUpdateView.as_view(), name='famille-edit'),
    path('famille/<int:pk>/delete/', views.FamilleDeleteView.as_view(), name='famille-delete'),
    path('famille/<int:pk>/print-info/', views.CoordonneesPDFView.as_view(), name='print-coord-famille'),
    path('famille/suivis_archives/', views.SuivisArchivesView.as_view(), name='suivis-archives'),
    path('famille/<int:pk>/personne/add/', views.PersonneCreateView.as_view(), name="personne-add"),

    # Prestations
    path('famille/<int:pk>/prestation/list/', views.PrestationListView.as_view(),
         name='prestation-famille-list'),
    path('famille/<int:pk>/enfant/<int:pk_pers>/prestation/list/', views.PrestationListView.as_view(),
         name='prestation-enfant-list'),
    path('famille/<int:pk>/enfant/<int:pk_pers>/prestation/add/', views.PrestationCreateView.as_view(),
         name='prestation-enfant-add'),
    path('famille/<int:pk>/prestation/<int:obj_pk>/edit/', views.PrestationUpdateView.as_view(),
         name='prestation-edit'),
    path('famille/<int:pk>/prestation/<int:obj_pk>/delete/', views.PrestationDeleteView.as_view(),
         name='prestation-delete'),
    path('prestation/<int:obj_pk>/deletefile/', views.PrestationDeleteFile.as_view(),
         name='prestation-deletefile'),
    path('utilisateur/prestations/', views.PrestationUtilisateurListView.as_view(), {'unite': 'cipe'},
         name='prestations-utilisateur'),
    path('prestation_gen/add/', views.PrestationGenEditView.as_view(is_create=True),
         name='prestation-gen-add'),
    path('prestation_gen/<int:pk>/edit/', views.PrestationGenEditView.as_view(is_create=False),
         name='prestation-gen-edit'),
    path('prestation_gen/<int:pk>/delete/', views.PrestationGenDeleteView.as_view(),
         name='prestation-gen-delete'),

    path('famille/<int:pk>/enfant/<int:pk_pers>/perinatal/', views.EnfantPerinatalView.as_view(),
         name='enfant-perinatal'),
    path('lieuacc/auto/', views.LieuAccouchementAutocompleteView.as_view(), name='lieuacc-autocomplete'),
    path('famille/<int:pk>/enfant/<int:pk_pers>/psycho/', views.EnfantPsychoView.as_view(), name='enfant-psycho'),
    path('famille/<int:pk>/enfant/<int:pk_pers>/psychoedit/', views.EnfantPsychoEditView.as_view(),
         name='enfant-psychoedit'),
    path('famille/<int:pk>/psychoedit/<int:pk_item>/', views.EnfantPsychoEditView.as_view(),
         name='item-psychoedit'),

    # Percentile
    path('enfant/<int:pk>/percentile/poids/', views.PercentileView.as_view(), {'typ': 'poids'},
         name='enfant-percentile-poids'),
    path('enfant/<int:pk>/percentile/taille/', views.PercentileView.as_view(), {'typ': 'taille'},
         name='enfant-percentile-taille'),
    path('enfant/<int:pk>/print/percentile/poids/', views.PercentilePoidsPDFView.as_view(),
         name='print-percentile-poids'),
    path('enfant/<int:pk>/print/percentile/taille/', views.PercentileTaillePDFView.as_view(),
         name='print-percentile-taille'),
    path('enfant/<int:pk>/percentile/email/', views.PercentileByEmailView.as_view(),
         name='enfant-percentile-email'),
    path('enfant/<int:pk>/archiver/', archive_views.ArchiveCreateView.as_view(default_unite="cipe"),
         name='enfant-archiver'),
    path('archive/<int:pk>/desarchiver/', archive_views.ArchiveCIPEDecryptView.as_view(),
         name='enfant-desarchiver'),

    # Thèmes de santé
    path('themesante/list/', views.ThemeSanteListView.as_view(), name='themesante-list'),
    path('themesante/add/', views.ThemeSanteEditView.as_view(is_create=True), name='themesante-add'),
    path('themesante/<int:pk>/edit/', views.ThemeSanteEditView.as_view(), name='themesante-edit'),
    path('themedoc/list/', views.ThemeDocListView.as_view(), name='themedoc-list'),
    path('themedoc/add/', views.ThemeDocEditView.as_view(is_create=True), name='themedoc-add'),
    path('themedoc/<int:pk>/edit/', views.ThemeDocEditView.as_view(), name='themedoc-edit'),
    path('themedoc/<int:pk>/delete/', views.ThemeDocDeleteView.as_view(), name='themedoc-delete'),

    path('documents/', views.GeneralDocListView.as_view(), name='generaldoc-list'),
    path('documents/add/', views.GeneralDocEditView.as_view(is_create=True), name='generaldoc-add'),
    path('documents/<int:pk>/edit/', views.GeneralDocEditView.as_view(), name='generaldoc-edit'),
    path('documents/<int:pk>/delete/', views.GeneralDocDeleteView.as_view(), name='generaldoc-delete'),
    path('documents/categ/<int:pk>/edit/', views.GeneralDocCategEditView.as_view(), name='generaldoccateg-edit'),

    # Stats
    path('statistiques/familles/', views_stats.StatistiquesFamillesView.as_view(), name='stats-familles'),
    path('statistiques/interv/', views_stats.StatistiquesParIntervView.as_view(), name='stats-interv'),
    path('statistiques/localites/', views_stats.StatistiquesLocalitesView.as_view(), name='stats-localites'),
    path('statistiques/lieux/', views_stats.StatistiquesLieuxView.as_view(), name='stats-lieux'),
    path('statistiques/type/', views_stats.StatistiquesTypeView.as_view(), name='stats-type'),
    path('statistiques/nouvelles/', views_stats.StatistiquesNouvellesView.as_view(), name='stats-nouvelles'),
    path('statistiques/themes/', views_stats.StatistiquesThemesView.as_view(), name='stats-themes'),
    path('statistiques/nationalite/', views_stats.StatistiquesNationaliteView.as_view(),
         name='stats-nationalite'),
    path('statistiques/duree/', views_stats.StatistiquesDureeView.as_view(), name='stats-duree'),
    path('statistiques/gen/', views_stats.StatistiquesGenView.as_view(), name='stats-gen'),
    path('statistiques/export/', views_stats.StatistiquesExportView.as_view(), name='stats-export'),
    path('statistiques/export/santene/', views_stats.StatistiquesSanteNEView.as_view(),
         name='stats-export-santene'),
    path('statistiques/export/ascpe/', views_stats.StatistiquesASCPEView.as_view(), name='stats-export-ascpe'),
]

templates/404-public.html
{% extends "base-public.html" %}

{% block title %}Page introuvable{% endblock %}

{% block content %}
  <h2>Page introuvable</h2>
  <p>Nous sommes désolés, la page demandée n'existe pas ou plus.</p>
{% endblock %}

templates/actions.html
<div id="actions" class="row border-top mt-2">
        {% if form.instance.pk %}
        <div class="col mt-3">
            {% if view.delete_url %}
            <button class="btn btn-sm btn-danger" name="delete" type="button"
                data-confirm="Voulez-vous vraiment supprimer cet objet ?"
                formaction="{{ view.delete_url }}"
                >Supprimer</button>
            {% endif %}
        </div>
        {% endif %}
        <div class="col mt-3 text-end">
            <a class="btn btn-sm btn-secondary" href="javascript: history.go(-1)">Annuler</a>
            <button class="btn btn-sm btn-success" name="save" type="submit">Enregistrer</button>
        </div>
</div>

templates/base-public.html
<!DOCTYPE html>
<html lang="fr-FR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %} | Croix-Rouge neuchâteloise</title>
    <link rel="icon" type="image/png" href="{% static 'favicon.png' %}" sizes="16x16">
    <link rel="stylesheet" type="text/css" href="{% static 'css/public.css' %}">
    {% block extrastyle %}{% endblock %}
    {% block extra_javascript %}{% endblock %}
</head>

<body>
    <div id="wrapper">
        <header>
            <div class="frame">
                <a href="https://croix-rouge-ne.ch"><img class="logo" src="{% static 'img/logo-cr.svg' %}" alt="Croix-Rouge neuchâteloise"></a>
                <div class="panel">
                    <div class="menu">
                        <ul class="add-nav">
                            <li id="menu-item-1823" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1823"><a href="https://croix-rouge-ne.ch/nos-coordonnees/">Contact</a></li>
                            <li id="menu-item-2133" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-2133"><a href="https://croix-rouge-ne.ch/agir-avec-nous/">Agir avec nous</a></li>
                            <li id="menu-item-2293" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-2293"><a href="https://croix-rouge-ne.ch/formulaire-don/">Faire un DON</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </header>
        <main>
            <div class="frame">
                {% block messages %}
                {% if messages %}
                    <div class="text-section">
                        <ul class="list-unstyled messages">
                            {% for message in messages %}
                                <li class="alert {{ message.tags }}">{{ message|linebreaksbr|capfirst }}</li>
                            {% endfor %}
                        </ul>
                    </div>
                {% endif %}
                {% endblock messages %}

                {% block content %}
                {% endblock %}
            </div>
        </main>
        <footer>
            <p>© 2021 Croix-Rouge neuchâteloise</p>
        </footer>
    </div>
</body>
</html>

templates/base.html
<!DOCTYPE html>
<html lang="fr">
    <head>
        <title>Croix-Rouge NE / {% block title %}{{ source|upper }}{% endblock %}</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        {% include 'bootstrap_headers.html' %}

        <link rel="stylesheet" type="text/css" href="{% static 'admin/css/dashboard.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'admin/css/widgets.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/tablesort.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
        <link rel="icon" type="image/png" href="{% static 'favicon.png' %}" sizes="16x16">
        {% block extrastyle %}{% endblock %}

        <script src="{% url 'javascript-catalog' %}"></script>
        <script src="{% static 'admin/js/core.js' %}" defer></script>
        <script src="{% static 'admin/js/calendar.js' %}" defer></script>
        <script src="{% static 'js/DateTimeShortcuts.js' %}" defer></script>
        <script src="{% static 'js/tablesort.min.js' %}" defer></script>
        <script src="{% static 'js/sorts/tablesort.number.min.js' %}" defer></script>
        <script src="{% static 'js/autosize.min.js' %}" defer></script>
        <script src="{% static 'js/main.js' %}" defer></script>
        {% block extra_javascript %}{% endblock %}
        {{ form.media }}
    </head>
    <body>
        <div class="top-container">
            {% block header %}
            <header>
                <figure class="mb-0">
                    <img id="logo-cr" src="{% static 'img/logo-cr.svg' %}">
                    <img id="bandeau-cr" src="{% static 'img/bandeau_rouge.png' %}">
                </figure>
            </header>
            {% include 'user_bar.html' %}
            {% endblock %}
            {% block top-navigation %}
            <nav class="container-fluid border-bottom">
                <div class="row bg-light">
                    <div class="col-sm-6">
                        {% block nav-left %}
                        {% if user.is_authenticated %}
                            <nav id="menu_crne" class="navbar navbar-expand-lg">
                                <ul class="navbar-nav py-2">
                                    <li class="nav-item">
                                        <a href="{% url 'home' %}" class="btn btn-sm btn-outline-secondary" role="button">Accueil</a>
                                    </li>
                                    {% if source %}
                                        {% include source|add:'/menu_principal.html' %}
                                    {% else %}
                                        {% include 'admin/menu_principal.html' %}
                                    {% endif %}
                                </ul>
                            </nav>
                        {% endif %}
                        {% endblock %}
                    </div>
                    <div class="col-sm-6 ps-0 text-end pt-2">
                        {% block boutons_droite %}{% endblock %}
                    </div>
                </div>
            </nav>
            {% endblock %}

            {% block messages %}
                {% if messages %}
                    <div class="mt-3">
                        <div class="col-xl-10 offset-xl-1">
                            <ul class="list-unstyled messages">
                                {% for message in messages %}
                                    <li class="alert {{ message.tags }}">{{ message|linebreaksbr|capfirst }}</li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                {% endif %}
            {% endblock messages %}

            {% block above-content %}{% endblock %}
            <section class="mt-3 main-content container-fluid">
              <div class="row">
                <div class="col-xl-10 offset-lg-1">
                    {% block content %}{% endblock %}
                    {% block pagination %}
                        {% include 'pagination.html' %}
                    {% endblock %}
                </div>
              </div>
            </section>

            <footer>
                <div class="footer text-center p-4 border-top pl-0 pr-0">
                    Croix-Rouge neuchâteloise
                </div>
            </footer>
        </div>

    <!-- Fenêtre pour l’édition d’objets en fenêtre modale -->
    <div id="popup0" class="modal" role="dialog">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title"></h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body"></div>
        </div>
      </div>
    </div>

    <!-- simple modal for images -->
    <div id="imgModal" class="modal modal-image">
      <span id="modalClose">&times;</span>
      <img class="modal-content" id="img01">
      <div id="caption"></div>
    </div>
    </body>
</html>

templates/bootstrap_headers.html
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">

<script src="{% static 'admin/js/vendor/jquery/jquery.min.js' %}"></script>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>

templates/index.html
<!DOCTYPE html>
<html lang="fr">
<head>
    <title>Croix-Rouge NE</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% include 'bootstrap_headers.html' %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
</head>
<body>
    <div id="bg_home" class="top-container p-0 m-0">
        <section class="main-content">
        {% include 'user_bar.html' %}
        <div class="row g-3" id="home-app-line">
            <div class="col-sm-auto">
                <a class="btn btn-primary btn-lg me-3 mt-2" href="{% url 'spe-famille-list' %}" role="button">SPE</a>
            </div>
            <div class="col-sm-auto">
                <a class="btn btn-dark btn-lg me-3 mt-2" href="{% url 'cipe:famille-list' %}" role="button">CIPE</a>
            </div>
            {% if perms.amf.view_familleamf %}
                <div class="col-sm-auto">
                    <a class="btn btn-info btn-lg me-3 mt-2" href="{% url 'amf-famille-list' %}" role="button">AMF</a>
                </div>
            {% endif %}
            {% if perms.sof.view_famillesof %}
            <div class="col-sm-auto">
                <a class="btn btn-success btn-lg me-3 mt-2" href="{% url 'sof-famille-list' %}" role="button">SOF</a>
            </div>
            {% endif %}
            <div class="col-sm-auto">
                <a class="btn btn-light btn-lg mt-2" href="{% url 'utilisateur-list' %}" role="button">Administration</a>
            </div>
        </div>
        </section>

        <footer>
            <div class="col text-center footer p-4 border-top" >
                Croix-Rouge neuchâteloise
            </div>
        </footer>
    </div>
</body>
</html>

templates/login.html
{% extends "base.html" %}

{% block content %}
    <div id="login">
        <form class="form-horizontal" name="LoginForm" action="{% url 'login' %}" method="post">
        {% csrf_token %}
        <input type="hidden" name="next" value="{{ next }}">
        {% if form.non_field_errors %}
        {% for error in form.non_field_errors %}
        <p class="errornote">{{ error }}</p>
        {% endfor %}
        {% endif %}
        <div class="control-group">
            {{ form.username.label_tag }}
            <div class="controls">
                {{ form.username.errors }}{{ form.username }}
            </div>
        </div>
        <div class="control-group mt-3">
            {{ form.password.label_tag }}
            <div class="controls">
                {{ form.password.errors }}{{ form.password }}
            </div>
        </div>
        <div class="control-group mt-3">
            <div class="controls">
                <button type="submit" class="btn btn-primary">Se connecter</button>
            </div>
        </div>
        </form>
    </div>
{% endblock %}

templates/pagination.html
{% if is_paginated %}
<div id="pagination" aria-label="pagination" class="mt-5">
  <ul class="pagination pagination-sm justify-content-center flex-wrap">
    {% for i in paginator.page_range %}
      {% if page_obj.number == i %}
        <li class="page-item active"><span class="page-link">{{ i }}<span class="visually-hidden">(current)</span></span></li>
      {% else %}
        <li class="page-item" ><a class="page-link" href="{{ request.path }}?{% param_replace page=i %}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
  </ul>
</div>
{% endif %}

templates/partial_agenda_cloture.html
<h6 class="pb-2 fw-bold">Fin de l’accompagnement le</h6>
<p>{{ form.date_fin_suivi.errors }}{{ form.date_fin_suivi }}</p>
<h6 class="mt-2 fw-bold">Motif de fin</h6>
<p class="px-5 fin">{{ form.motif_fin_suivi.errors }}{{ form.motif_fin_suivi }}</p>
{% if form.destination %}
<h6 class="mt-2 fw-bold">Destination</h6>
<p class="px-5 fin">{{ form.destination.errors }}{{ form.destination }}</p>
{% endif %}

templates/partial_show_docs.html
{% for doc in docs %}
<div class="py-1">
    <a href="{{ doc.get_absolute_url }}">{{ doc.title }}</a>
    <a href="{{ doc.get_print_url }}">
        <img class="icon-xs" src="{% static 'img/printer.png' %}">
    </a>
</div>
{% endfor %}

templates/partial_table_documents.html
<table class="table table-sm table-borderless mb-3">
   <tr>
      <th class="left-label">Documents
         {% if famille|can_edit:user %}
         <span>
            <a href="{% url 'famille-doc-upload' famille.pk %}"
               class="btn btn-sm btn-mini btn-primary"
               role="button "
               title="Ajouter un document">+</a>
          </span>
         {% endif %}
      </th>
      <td colspan="4">
         <div>
            {% for doc in famille.documents.all %}
               <a href="{{ doc.fichier.url }}">{{ doc.titre }}</a>
               {% if famille|can_edit:user %}
               <span class="hoverimage">
                  <button type="submit" class="btn confirm"
                     formaction="{% url 'famille-doc-delete' famille.pk doc.pk %}"
                     title="Supprimer ce document"
                     data-confirm="Voulez-vous vraiment supprimer ce document ?">
                     <img src="{% static 'admin/img/icon-deletelink.svg' %}">
                  </button>
               </span>
               {% endif %}
            {% endfor %}
         </div>
      </td>
   </tr>
</table>

templates/user_bar.html
<div class="row">
    <div id="user-bar" class="col-xl-6 text-end">
            {% if user.is_authenticated %}
            <div id="user-tools" class="d-flex justify-content-end">
                <div class="p-1"><a href="{% url 'utilisateur-connecte' user.username %}">{% firstof user.get_short_name user.get_username %}</a> |</div>
                {% if perms.cipe.add_famillecipe %}<div class="p-1"><a href="{% url 'person-agenda' user.get_username %}">Mon agenda</a> |</div>{% endif %}
                <form method="post" class="d-inline p-1" action="{% url 'logout' %}">{% csrf_token %}
                    <button type="submit" class="btn btn-link p-0">Se déconnecter</button>
                </form>
            </div>
            {% endif %}
        <div class="col-xl-1"></div>
    </div>
</div>