amf/urls.py
from django.urls import path

from . import views, views_stats

urlpatterns = [
    # Famille
    path('famille/list/', views.FamilleListView.as_view(), name='amf-famille-list'),
    path('famille/suivis-termines/', views.FamilleListView.as_view(mode='termines'),
         name='amf-famille-suivis-termines'),
    path('famille/add/', views.FamilleCreateView.as_view(), name='amf-famille-add'),
    path('famille/<int:pk>/edit/', views.FamilleUpdateView.as_view(), name='amf-famille-edit'),
    path('famille/<int:pk>/suivi/', views.AMFSuiviView.as_view(), name='amf-famille-suivi'),

    # Journal
    path('famille/<int:pk>/prestation/list/', views.PrestationListView.as_view(), name='amf-journal-list'),
    path('famille/<int:pk>/prestation/add/', views.PrestationCreateView.as_view(), name='amf-prestation-famille-add'),
    path('famille/<int:pk>/prestation/<int:obj_pk>/edit/', views.PrestationUpdateView.as_view(),
         name='amf-prestation-edit'),
    path('famille/<int:pk>/prestation/<int:obj_pk>/delete/', views.PrestationDeleteView.as_view(),
         name='amf-prestation-delete'),

    path('formation/list/', views.FormationListView.as_view(), name="amf-formation-list"),
    path('formation/add/', views.FormationCreateView.as_view(), name="amf-formation-add"),
    path('formation/<int:pk>/edit/', views.FormationUpdateView.as_view(), name="amf-formation-edit"),
    path('formation/<int:pk>/inscription/', views.FormationInscriptionView.as_view(),
         name="amf-formation-inscription"),
    path('famille/<int:pk>/inscription/autocomplete/', views.ParticipantsFormationAutocomplete.as_view(),
         name='amf-inscription-autocomplete'),

    path('stats/familles/', views_stats.StatistiquesFamillesView.as_view(), name='amf-stats-familles'),

    path('importation-spaj/', views.ImportationSPAJView.as_view(), name='amf-importation'),
]

spe/urls.py
from django.urls import path

from croixrouge import views as cr_views

from . import views, views_stats
from .forms import BilanForm
from .models import Bilan

urlpatterns = [
    # Famille
    path('famille/list/', views.FamilleListView.as_view(), name='spe-famille-list'),
    path('famille/attente/', views.FamilleListView.as_view(mode='attente'), name='spe-famille-attente'),
    path('famille/add/', views.FamilleCreateView.as_view(), name='spe-famille-add'),
    path('famille/<int:pk>/edit/', views.FamilleUpdateView.as_view(), name='spe-famille-edit'),
    path('famille/<int:obj_pk>/niveau/add/', views.NiveauSPECreateUpdateView.as_view(), name='spe-niveau-add'),
    path('famille/<int:obj_pk>/niveau/<int:pk>/edit/', views.NiveauSPECreateUpdateView.as_view(),
         name='spe-niveau-edit'
         ),
    path('famille/<int:obj_pk>/niveau/<int:pk>/delete/', views.NiveauSPEDeleteView.as_view(),
         name='spe-niveau-delete'),

    # Prestations
    path('prestation/menu/', views.PrestationMenu.as_view(), name='spe-prestation-menu'),
    path('famille/<int:pk>/prestation/list/', views.PrestationListView.as_view(), name='spe-journal-list'),
    path('famille/<int:pk>/prestation/add/', views.PrestationCreateView.as_view(), name='spe-prestation-famille-add'),
    path('famille/<int:pk>/prestation/<int:obj_pk>/edit/', views.PrestationUpdateView.as_view(),
         name='spe-prestation-edit'),
    path('famille/<int:pk>/prestation/<int:obj_pk>/delete/', views.PrestationDeleteView.as_view(),
         name='spe-prestation-delete'),
    path('prestation_gen/list/', views.PrestationListView.as_view(), name='spe-prestation-gen-list'),
    path('prestation_gen/add/', views.PrestationCreateView.as_view(), name='spe-prestation-gen-add'),

    # Doc. à imprimer
    path('famille/<int:pk>/print-evaluation/', views.EvaluationPDFView.as_view(), name='spe-print-evaluation'),
    path('famille/<int:pk>/print-info/', views.CoordonneesPDFView.as_view(), name='spe-print-coord-famille'),
    path('famille/<int:pk>/print-journal', views.JournalPDFView.as_view(), name='spe-print-journal'),
    path('bilan/<int:pk>/print/', views.BilanPDFView.as_view(), name='spe-print-bilan'),

    # Demande, suivi, agenda, suivis terminés
    path('famille/<int:pk>/demande/', views.DemandeView.as_view(), name='spe-demande'),
    path('famille/<int:pk>/suivi/', views.SPESuiviView.as_view(), name='spe-famille-suivi'),
    path('famille/<int:pk>/intervenant/add/', views.SuiviIntervenantCreate.as_view(), name='spe-intervenant-add'),
    path('famille/<int:pk>/intervenant/<int:obj_pk>/edit/', views.SuiviIntervenantUpdateView.as_view(),
         name='spe-intervenant-edit'),
    path('famille/<int:pk>/agenda/', views.AgendaSuiviView.as_view(), name='spe-famille-agenda'),
    path('famille/<int:pk>/bilan/add/',
         cr_views.BilanEditView.as_view(model=Bilan, form_class=BilanForm, is_create=True),
         name='famille-bilanspe-add'),
    path('famille/<int:pk>/bilan/<int:obj_pk>/', cr_views.BilanDetailView.as_view(model=Bilan),
         name='famille-bilanspe-view'),
    path('famille/<int:pk>/bilan/<int:obj_pk>/edit/',
         cr_views.BilanEditView.as_view(model=Bilan, form_class=BilanForm),
         name='famille-bilanspe-edit'),
    path('famille/<int:pk>/bilan/<int:obj_pk>/delete/', cr_views.BilanDeleteView.as_view(model=Bilan),
         name='famille-bilanspe-delete'),
    path('famille/archivable/list/', views.FamilleArchivableListe.as_view(), name='spe-famille-archivable'),

    path('suivis_termines/', views.SuivisTerminesListView.as_view(), name='spe-suivis-termines'),
    path('charge_utilisateurs/', views.UtilisateurChargeDossierView.as_view(), name='charge-utilisateurs'),
    path('duo/edit/<path:sigles>/', views.DuoSPERdvEditView.as_view(), name='duo-date-change'),

    path('medlink/import/', views.MedlinkImportView.as_view(), name='medlink-import'),
    path('medlink/historique/', views.MedlinkHistoriqueView.as_view(), name='medlink-historique'),
    path('medlink/detail/', views.MedlinkDetailView.as_view(), name='medlink-detail'),

    # Statistiques
    path('statistiques/', views_stats.StatistiquesView.as_view(), name='stats'),
    path('statistiques/localite/', views_stats.StatistiquesParLocaliteView.as_view(), name='stats-localite'),
    path('statistiques/region/', views_stats.StatistiquesParRegionView.as_view(), name='stats-region'),
    path('statistiques/duree/', views_stats.StatistiquesParDureeView.as_view(), name='stats-duree'),
    path('statistiques/age/', views_stats.StatistiquesParAgeView.as_view(), name='stats-age'),
    path('statistiques/niveaux/', views_stats.StatistiquesParNiveauView.as_view(), name='stats-niveaux'),
    path('statistiques/motifs/', views_stats.StatistiquesMotifsView.as_view(), name='stats-motifs'),
    path('statistiques/prestations/spe/', views_stats.StatistiquesPrestationView.as_view(),
         {'unite': 'spe'}, name='stats-prestation-spe'),
    path('statistiques/ressources/', views_stats.StatistiquesRessourcesView.as_view(), name='stats-ressources'),

    path('export/prestation/', views.ExportPrestationView.as_view(), name='export-prestation'),
]

spe/forms.py
from datetime import date, datetime, time, timedelta

from city_ch_autocomplete.forms import CityChField, CityChMixin
from django import forms
from django.db.models import Count, Q
from django.utils.html import escape
from django.utils.safestring import mark_safe

from croixrouge.forms import (
    AgendaFormBase,
    BootstrapMixin,
    BSCheckboxSelectMultiple,
    FamilleFormBase,
    PickDateWidget,
    PrestationFormBase,
    ReadOnlyableMixin,
    RichTextField,
)
from croixrouge.models import Contact, EquipeChoices, LibellePrestation, Personne, Role, Utilisateur
from croixrouge.utils import CSVFile, XLSXFile, unaccent

from .models import Bilan, DuoSPERdv, FamilleSPE, IntervenantSPE, NiveauSPE, PrestationSPE, SuiviSPE


class EquipeFilterForm(forms.Form):
    equipe = forms.ChoiceField(
        label="Équipe", choices=[('', 'Toutes')] + EquipeChoices.choices, required=False,
        widget=forms.Select(attrs={'class': 'form-select form-select-sm immediate-submit'}),
    )

    def filter(self, familles):
        if self.cleaned_data['equipe']:
            familles = familles.filter(suivispe__equipe=self.cleaned_data['equipe'])
        return familles


class FamilleFilterForm(EquipeFilterForm):
    ressource = forms.ChoiceField(
        label='Ressources',
        required=False,
        widget=forms.Select(attrs={'class': 'form-select form-select-sm immediate-submit'})
    )
    niveau = forms.ChoiceField(
        label="Niv. d'interv.",
        required=False,
        widget=forms.Select(attrs={'class': 'form-select form-select-sm immediate-submit'})
    )
    interv = forms.ChoiceField(
        label="Intervenant-e",
        required=False,
        widget=forms.Select(attrs={'class': 'form-select form-select-sm immediate-submit'})
    )
    nom = forms.CharField(
        widget=forms.TextInput(
            attrs={'placeholder': 'Nom de famille…', 'autocomplete': 'off',
                   'class': 'form-control form-control-sm inline'}),
        required=False
    )
    duos = forms.ChoiceField(
        label="Duos Educ/Psy",
        required=False,
        widget=forms.Select(attrs={'class': 'form-select form-select-sm immediate-submit'})
    )

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        intervenants = Utilisateur.objects.filter(is_active=True, groups__name='spe')
        self.fields['interv'].choices = [
            ('', 'Tout-e-s'), ('0', 'Aucun')] + [
            (user.id, user.nom_prenom) for user in intervenants
        ]
        self.fields['niveau'].choices = [
            ('', 'Tous')
        ] + [(key, val) for key, val in NiveauSPE.INTERV_CHOICES]

        self.fields['ressource'].choices = [
            ('', 'Toutes')
        ] + [(el.pk, el.nom) for el in Role.objects.filter(
                nom__in=['ASE', 'IPE', 'Coach APA', 'Assistant-e social-e']
            )]
        self.fields['duos'].choices = [
            ('', 'Tous')
        ] + [
            (duo, duo) for duo in FamilleSPE.objects.exclude(
                suivispe__date_fin_suivi__isnull=False
            ).with_duos().exclude(duo='').values_list('duo', flat=True).distinct().order_by('duo')
        ]

    def filter(self, familles):
        if self.cleaned_data['interv']:
            if self.cleaned_data['interv'] == '0':
                familles = familles.annotate(
                    num_interv=Count('suivispe__intervenants', filter=(
                        Q(suivispe__intervenantspe__date_fin__isnull=True) |
                        Q(suivispe__intervenantspe__date_fin__gt=date.today())
                    ))
                ).filter(num_interv=0)
            else:
                familles = familles.filter(
                    Q(suivispe__intervenantspe__intervenant=self.cleaned_data['interv']) & (
                        Q(suivispe__intervenantspe__date_fin__isnull=True) |
                        Q(suivispe__intervenantspe__date_fin__gt=date.today())
                    )
                )

        if self.cleaned_data['nom']:
            familles = familles.filter(nom__istartswith=self.cleaned_data['nom'])

        familles = super().filter(familles)

        if self.cleaned_data['niveau']:
            familles = familles.with_niveau_interv().filter(niveau_interv=self.cleaned_data['niveau'])

        if self.cleaned_data['ressource']:
            ress = IntervenantSPE.objects.actifs().filter(
                role=self.cleaned_data['ressource'],
            ).values_list('intervenant', flat=True)
            familles = familles.filter(suivispe__intervenants__in=ress).distinct()

        if self.cleaned_data['duos']:
            familles = familles.with_duos().filter(duo=self.cleaned_data['duos'])
        return familles


class FamilleForm(FamilleFormBase):
    equipe = forms.ChoiceField(label="Équipe", choices=[('', '------')] + SuiviSPE.EQUIPES_CHOICES[:2])

    # Concernant 'npa' & 'location', ils sont en lecture seule ici => pas besoin de faire de l'autocomplete

    class Meta:
        model = FamilleSPE
        fields = ['nom', 'rue', 'npa', 'localite', 'telephone', 'region', 'autorite_parentale',
                  'monoparentale', 'statut_marital', 'connue', 'accueil', 'garde',
                  'provenance', 'statut_financier']

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        if self.instance and self.instance.pk:
            self.initial['equipe'] = kwargs['instance'].suivi.equipe
        self.fields['provenance'].choices = [
            ch for ch in self.fields['provenance'].choices
            if (ch[0] != 'autre' or self.instance.provenance == 'autre')
        ]

    def save(self, **kwargs):
        famille = super().save(**kwargs)
        if famille.suivi.equipe != self.cleaned_data['equipe']:
            famille.suivi.equipe = self.cleaned_data['equipe']
            famille.suivi.save()
        return famille


class FamilleCreateForm(CityChMixin, FamilleForm):
    motif_detail = forms.CharField(
        label="Motif de la demande", widget=forms.Textarea(), required=False
    )
    typ = 'spe'
    city_auto = CityChField(required=False)
    postal_code_model_field = 'npa'
    city_model_field = 'localite'
    field_order = ['nom', 'rue', 'city_auto']

    class Meta(FamilleForm.Meta):
        exclude = ['typ', 'destination']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['provenance'].choices = [
            ch for ch in self.fields['provenance'].choices if ch[0] != 'autre'
        ]

    def save(self, **kwargs):
        famille = self._meta.model.objects.create_famille(
            equipe=self.cleaned_data['equipe'], **self.instance.__dict__
        )
        famille.suivi.motif_detail = self.cleaned_data['motif_detail']
        famille.suivi.save()
        return famille


class SuiviSPEForm(ReadOnlyableMixin, forms.ModelForm):
    equipe = forms.TypedChoiceField(
        choices=[('', '-------')] + SuiviSPE.EQUIPES_CHOICES[:2], required=False
    )

    class Meta:
        model = SuiviSPE
        fields = [
            'equipe', 'heure_coord', 'ope_referent', 'ope_referent_2',
            'mandat_ope', 'service_orienteur', 'service_annonceur', 'motif_demande',
            'motif_detail', 'demande_prioritaire', 'demarche', 'collaboration',
            'ressource', 'crise', 'remarque', 'remarque_privee',
        ]
        widgets = {
            'mandat_ope': BSCheckboxSelectMultiple,
            'motif_demande': BSCheckboxSelectMultiple,
        }

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.fields['ope_referent'].queryset = Contact.membres_ope()
        self.fields['ope_referent_2'].queryset = Contact.membres_ope()


class IntervenantSPEForm(BootstrapMixin, forms.ModelForm):
    intervenant = forms.ModelChoiceField(
        queryset=Utilisateur.objects.filter(groups__name__startswith='spe').distinct().order_by('nom')
    )
    date_debut = forms.DateField(
        label='Date de début', initial=date.today(), widget=PickDateWidget()
    )

    class Meta:
        model = IntervenantSPE
        fields = ['intervenant', 'role', 'date_debut']

    def __init__(self, suivi=None, **kwargs):
        self.suivi = suivi
        super().__init__(**kwargs)
        self.fields['role'].queryset = Role.objects.filter(intervenant=True)

    def clean(self):
        if self.suivi.intervenantspe_set.filter(
            intervenant=self.cleaned_data['intervenant'], date_fin__isnull=True
        ).exists():
            self.add_error(None, "Cet intervenant est déjà actif sur ce suivi")
        return super().clean()

    def save(self, **kwargs):
        self.instance.suivi = self.suivi
        return super().save(**kwargs)


class IntervenantSPEEditForm(BootstrapMixin, forms.ModelForm):

    class Meta:
        model = IntervenantSPE
        fields = ['intervenant', 'role', 'date_debut', 'date_fin']
        widgets = {
            'date_debut': PickDateWidget(),
            'date_fin': PickDateWidget(),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['intervenant'].disabled = True
        self.fields['role'].disabled = True


class DemandeSPEForm(BootstrapMixin, ReadOnlyableMixin, forms.ModelForm):
    class Meta:
        model = SuiviSPE
        fields = (
            'dates_demande', 'ref_presents', 'pers_famille_presentes', 'autres_pers_presentes',
            'difficultes', 'aides', 'competences', 'disponibilites', 'autres_contacts', 'remarque'
        )
        field_classes = {
            'difficultes': RichTextField,
            'aides': RichTextField,
            'disponibilites': RichTextField,
            'competences': RichTextField,
        }
        widgets = {
            'autres_contacts': forms.Textarea(attrs={'cols': 120, 'rows': 4}),
            'remarque': forms.Textarea(attrs={'cols': 120, 'rows': 4}),
        }


class AgendaForm(ReadOnlyableMixin, AgendaFormBase):

spe/templates/spe/charge_utilisateurs.html
{% extends "base.html" %}

{% block content %}
    <div class="row border-bottom mb-3">
        <div class="col"><p class="lead">Charge des dossiers en cours par utilisateur (rôles psy et éduc)</p></div>
        <div class="col text-end">
            <form method="get" action="." class="inline">{{ filter_form }}</form>
            <a class="btn btn-sm btn-outline-primary" href="{% url 'utilisateur-list' %}">Utilisateurs</a>
        </div>
    </div>

    <div class="row">
        <div class="col">
            <table id="user_table" class="table table-sm table-striped sortable">
            <thead class="table-light">
                <tr><th></th>
                    <th class="text-end">Taux act.</th>
                    <th class="text-end" data-sort-method="number">Familles éval.</th>
                    <th class="text-end" data-sort-method="number">Familles suivies</th>
                    <th class="text-end" data-sort-method="number">Charge hebdo</th>
                    <th class="text-end" data-sort-method="number">Charge max.</th>
                    <th class="text-end" data-sort-method="number">Différence</th>
                </tr>
            </thead>
            <tbody>
                {% for util in utilisateurs %}
                <tr><td>{{ util }}</td>
                    <td class="text-end">{{ util.taux_activite }}%</td>
                    <td class="text-end">{{ util.nbre_eval }}</td>
                    <td class="text-end">{{ util.nbre_suivi }}</td>
                    <td class="text-end">{{ util.heures }}</td>
                    <td class="text-end">{{ util.charge_max }}</td>
                    <td class="text-end{% if util.charge_diff < 0 %} text-danger{% endif %}">{{ util.charge_diff }}</td></tr>
                {% endfor %}
            </tbody>
            </table>
        </div>
    </div>
{% endblock %}

spe/templates/spe/date_entretien_duo_change.html
{% block content %}
<div class="row justify-content-center">
    <div class="col">
        <p class="h4 border-bottom mb-4">Dates d'entretien pour duo</p>
        <form action="{{ request.path }}" method="post">{% csrf_token %}
            <div class="row mb-4">
                <div class="col-md-4 h6 pt-2">{{ form.rendez_vous.label_tag }}</div>
                <div class="col-md-8 h5">{{ form.rendez_vous }}{{ form.rendez_vous.errors }}</div>
            </div>
            <div id="actions" class="row border-top mt-2">
                <div class="col mt-3 text-end">
                    <button type="button" class="btn btn-sm btn-secondary" data-bs-dismiss="modal" aria-label="Close">Annuler</button>
                    <button class="btn btn-sm btn-success" name="save" type="submit">Enregistrer</button>
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock %}

spe/templates/spe/famille_boutons.html
<div id="spe_buttons">
<a class="btn btn-outline-primary btn-sm {% if active == 'coordonnees' %} active {% endif %}" href="{% url 'spe-famille-edit' famille.pk %}">Coordonnées</a>
<a class="btn btn-outline-primary btn-sm {% if active == 'demande' %} active {% endif %}" href="{% url 'spe-demande' famille.pk %}">Demande</a>
<a class="btn btn-outline-primary btn-sm {% if active == 'prestation' %} active {% endif %}" href="{% url 'spe-journal-list' famille.pk %}">Journal</a>
<a class="btn btn-outline-primary btn-sm {% if active == 'suivi' %} active {% endif %}" href="{% url 'spe-famille-suivi' famille.pk %}">Suivi</a>
<a class="btn btn-outline-primary btn-sm {% if active == 'agenda' %} active {% endif %}"
   href="{% url 'spe-famille-agenda' famille.pk %}">Agenda</a>
{% if perms.croixrouge.change_utilisateur %}
    <a class="btn btn-outline-primary btn-sm{% if active == 'acces' %} active{% endif %}" href="{% url 'famille-journalacces' famille.pk %}">Journal d’accès</a>
{% endif %}
</div>

spe/templates/spe/famille_list.html
{% extends "base.html" %}

{% block extra_javascript %}
<script type="text/javascript">
document.addEventListener("DOMContentLoaded", () => {
    document.querySelectorAll("#id_niveau, #id_interv, #id_equipe").forEach(el => {
        el.addEventListener('change', (ev) => { ev.target.form.submit(); });
    });
});
</script>
{% endblock %}

{% block boutons_droite %}
<div class="topnav-right text-start float-end">
    <form method="get" action=".">
        <div class="form-floating float-start pb-2">
            {{ form.duos }}{{ form.duos.label_tag }}
        </div>
        <div class="form-floating float-start pb-2 ms-1">
            {{ form.ressource }}{{ form.ressource.label_tag }}
        </div>
        <div class="form-floating float-start pb-2 ms-1">
            {{ form.equipe }}{{ form.equipe.label_tag }}
        </div>
        <div class="form-floating float-start ms-1">
            {{ form.interv }}{{ form.interv.label_tag }}
        </div>
        <div class="form-floating float-start ms-1" style="width:8em;">
            {{ form.niveau }}{{ form.niveau.label_tag }}
        </div>
        <div class="float-start input-group ms-1 mt-2" style="width:16em;">
            {{ form.nom }}
            <button class="px-2" type="submit" title="Rechercher">
                <img src="{% static 'admin/img/search.svg' %}">
            </button>
            <button id="reset-button" class="ms-1" type="reset" title="Réinitialiser tous les filtres">
                <img src="{% static 'img/filter_off.svg' %}">
            </button>
        </div>
    </form>
</div>
{% endblock %}

{% block content %}
    <div class="row border-bottom mb-3">
        <div class="col"><p class="lead">Familles SPE {% if view.mode == 'attente' %}- Liste d’attente{% endif %}</p></div>
        <div class="col text-end" >
            {% if view.mode == 'attente' %}
                <a class="btn btn-sm btn-outline-primary" href="{% url 'spe-famille-list' %}">Liste</a>
            {% else %}
                <a class="btn btn-sm btn-outline-primary" href="{% url 'spe-famille-attente' %}">Liste d’attente</a>
            {% endif %}
            {% if perms.spe.add_famillespe %}
                <a class="btn btn-sm btn-outline-primary" href="{% url 'spe-famille-add' %}">Nouvelle famille</a>
            {% endif %}
        </div>
    </div>
    <div class="row">
        <div class="col">
            <table id="benef_table" class="table table-sm table-hover sortable">
                <thead class="table-light">
                    <tr>
                    {% for label in labels %}
                        <th>{{ label }}</th>
                    {% endfor %}
                    </tr>
                </thead>
                <tbody>
                    {% for famille in object_list %}
                        {% with suivi=famille.suivi %}
                        <tr data-statut="{{ suivi.etape.code }}" data-intervenant="{{ suivi|referents_pk_data }}">
                            {% for col_key in col_keys %}
                            {% if col_key == 'nom' %}
                                <td>
                                    <div>
                                        <a href="{% url 'spe-famille-suivi' famille.pk %}" title="Suivi">{{ famille.nom }}</a>
                                        <span class="hoverimage">
                                            <a class="btn btn-sm m-0 p-0" role="button"
                                               href="{% url 'spe-famille-edit' famille.pk %}"
                                               title="{{ famille.telephone }}">
                                                <img src="{% static 'img/coordonnees.gif' %}" width="15" height="15">
                                            </a>
                                        </span>
                                    </div>
                                </td>
                            {% elif col_key == 'localite' %}
                            <td>{{ famille.npa}} {{ famille.localite }}</td>
                            {% elif col_key == 'referents' %}
                            <td>{{ suivi|sigles_referents }}</td>
                            {% elif col_key == 'referents_ope' %}
                            <td>
                                {{ suivi.ope_referent|info_ope }}
                            </td>
                            {% elif col_key == 'suivi' %}
                            <td data-sort="{{ famille.suivi.etape.num }}">
                                <table class="statut_suivi">
                                    <tr><td>{{ suivi|etape_cellule:"demande" }}</td>
                                        <td>{{ suivi|etape_cellule:"debut_evaluation" }}</td>
                                        <td>{{ suivi|etape_cellule:"fin_evaluation" }}</td>
                                        <td>{{ suivi|etape_cellule:"debut_suivi" }}</td>
                                        <td>{{ suivi|etape_cellule:"bilan_suivant" }}</td>
                                        <td>{{ suivi|etape_cellule:"resume" }}</td>
                                        <td>{{ suivi|etape_cellule:"fin_suivi" }}</td>
                                    </tr>
                                </table>
                            </td>
                            {% elif col_key == 'prioritaire' %}
                            <td class="text-center">{{ suivi.demande_prioritaire|yesno:'Oui,' }}</td>
                            {% elif col_key == 'niveau_interv' %}
                            <td class="text-center">{{ famille.niveau_interv|default_if_none:'-' }}</td>
                            {% elif col_key == 'date_demande' %}
                            <td data-sort="{{ suivi.date_demande|date:'Ymd' }}">
                                {{ suivi.date_demande|date:"d.m.Y" }}
                            </td>
                            {% elif col_key == 'region' %}
                            <td>{{ famille.region.nom }}</td>
                            {% elif col_key == 'evaluation' %}
                                {% if suivi.date_fin_evaluation %}<td class="green">Terminée le {{ suivi.date_fin_evaluation }}</td>
                                {% elif suivi.date_debut_evaluation %}<td class="orange">En cours</td>
                                {% else %}<td class="red">À faire</td>{% endif %}
                            {% endif %}
                        {% endfor %}
                        </tr>
                        {% endwith %}
                    {% empty %}
                        <td colspan="8" class="bg-warning" align="center">
                            <i>Aucune famille ne correspond à votre recherche.</i>
                        </td>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    {% if can_view_rdvs %}
    <div class="alert alert-secondary">
        {% if duo_rdv_passes %}
        <div>Derniers RdV:
            {% for rdv in duo_rdv_passes %}{% if not forloop.first %}, {% endif %}{{ rdv.rendez_vous|date:'d.m.Y' }}{% endfor %}
        </div>
        {% endif %}
        <div>
            Prochain RdV pour {{ form.duos.value }}:
            {% if can_edit_rdvs %}<a href="{% url 'duo-date-change' form.duos.value %}" class="js-edit">{% endif %}
            {% if prochain_duo_rdv %}{{ prochain_duo_rdv.rendez_vous|date:'d.m.Y' }}{% else %}<i>à définir</i>{% endif %}
            {% if can_edit_rdvs %}</a>{% endif %}
        </div>
    </div>
    {% endif %}

    {% if ma_charge %}
    <div class="alert alert-info">
        Ma charge actuelle: {{ ma_charge.nbre_eval }} familles en éval., {{ ma_charge.nbre_suivi }} familles suivies, {{ ma_charge.heures|default_if_none:0 }}h. hebdo (sur max. {{ user.charge_max}}h)
    </div>
    {% endif %}
{% endblock %}