amf/urls.py
from django.urls import path

from . import views, views_stats

urlpatterns = [
    # Famille
    path('famille/list/', views.FamilleListView.as_view(), name='amf-famille-list'),
    path('famille/suivis-termines/', views.FamilleListView.as_view(mode='termines'),
         name='amf-famille-suivis-termines'),
    path('famille/add/', views.FamilleCreateView.as_view(), name='amf-famille-add'),
    path('famille/<int:pk>/edit/', views.FamilleUpdateView.as_view(), name='amf-famille-edit'),
    path('famille/<int:pk>/suivi/', views.AMFSuiviView.as_view(), name='amf-famille-suivi'),

    # Journal
    path('famille/<int:pk>/prestation/list/', views.PrestationListView.as_view(), name='amf-journal-list'),
    path('famille/<int:pk>/prestation/add/', views.PrestationCreateView.as_view(), name='amf-prestation-famille-add'),
    path('famille/<int:pk>/prestation/<int:obj_pk>/edit/', views.PrestationUpdateView.as_view(),
         name='amf-prestation-edit'),
    path('famille/<int:pk>/prestation/<int:obj_pk>/delete/', views.PrestationDeleteView.as_view(),
         name='amf-prestation-delete'),

    path('formation/list/', views.FormationListView.as_view(), name="amf-formation-list"),
    path('formation/add/', views.FormationCreateView.as_view(), name="amf-formation-add"),
    path('formation/<int:pk>/edit/', views.FormationUpdateView.as_view(), name="amf-formation-edit"),
    path('formation/<int:pk>/inscription/', views.FormationInscriptionView.as_view(),
         name="amf-formation-inscription"),
    path('famille/<int:pk>/inscription/autocomplete/', views.ParticipantsFormationAutocomplete.as_view(),
         name='amf-inscription-autocomplete'),

    path('stats/familles/', views_stats.StatistiquesFamillesView.as_view(), name='amf-stats-familles'),

    path('importation-spaj/', views.ImportationSPAJView.as_view(), name='amf-importation'),
]

cipe/urls.py
from django.urls import path

from archive import views as archive_views
from croixrouge.views import FamilleAutoCompleteView

from . import views, views_stats

app_name = "cipe"
urlpatterns = [
    path('famille/cipe/dal/', FamilleAutoCompleteView.as_view(typ='cipe'), name="famille-autocomplete"),
    path('famille/cipe/can_sms/', views.FamilleHasSMSView.as_view(), name="famille-can-sms"),

    # Famille
    path('famille/list/', views.FamilleListView.as_view(), name='famille-list'),
    path('famille/add/', views.FamilleCreateView.as_view(), name='famille-add'),
    path('famille/<int:pk>/edit/', views.FamilleUpdateView.as_view(), name='famille-edit'),
    path('famille/<int:pk>/delete/', views.FamilleDeleteView.as_view(), name='famille-delete'),
    path('famille/<int:pk>/print-info/', views.CoordonneesPDFView.as_view(), name='print-coord-famille'),
    path('famille/suivis_archives/', views.SuivisArchivesView.as_view(), name='suivis-archives'),
    path('famille/<int:pk>/personne/add/', views.PersonneCreateView.as_view(), name="personne-add"),

    # Prestations
    path('famille/<int:pk>/prestation/list/', views.PrestationListView.as_view(),
         name='prestation-famille-list'),
    path('famille/<int:pk>/enfant/<int:pk_pers>/prestation/list/', views.PrestationListView.as_view(),
         name='prestation-enfant-list'),
    path('famille/<int:pk>/enfant/<int:pk_pers>/prestation/add/', views.PrestationCreateView.as_view(),
         name='prestation-enfant-add'),
    path('famille/<int:pk>/prestation/<int:obj_pk>/edit/', views.PrestationUpdateView.as_view(),
         name='prestation-edit'),
    path('famille/<int:pk>/prestation/<int:obj_pk>/delete/', views.PrestationDeleteView.as_view(),
         name='prestation-delete'),
    path('prestation/<int:obj_pk>/deletefile/', views.PrestationDeleteFile.as_view(),
         name='prestation-deletefile'),
    path('utilisateur/prestations/', views.PrestationUtilisateurListView.as_view(), {'unite': 'cipe'},
         name='prestations-utilisateur'),
    path('prestation_gen/add/', views.PrestationGenEditView.as_view(is_create=True),
         name='prestation-gen-add'),
    path('prestation_gen/<int:pk>/edit/', views.PrestationGenEditView.as_view(is_create=False),
         name='prestation-gen-edit'),
    path('prestation_gen/<int:pk>/delete/', views.PrestationGenDeleteView.as_view(),
         name='prestation-gen-delete'),

    path('famille/<int:pk>/enfant/<int:pk_pers>/perinatal/', views.EnfantPerinatalView.as_view(),
         name='enfant-perinatal'),
    path('lieuacc/auto/', views.LieuAccouchementAutocompleteView.as_view(), name='lieuacc-autocomplete'),
    path('famille/<int:pk>/enfant/<int:pk_pers>/psycho/', views.EnfantPsychoView.as_view(), name='enfant-psycho'),
    path('famille/<int:pk>/enfant/<int:pk_pers>/psychoedit/', views.EnfantPsychoEditView.as_view(),
         name='enfant-psychoedit'),
    path('famille/<int:pk>/psychoedit/<int:pk_item>/', views.EnfantPsychoEditView.as_view(),
         name='item-psychoedit'),

    # Percentile
    path('enfant/<int:pk>/percentile/poids/', views.PercentileView.as_view(), {'typ': 'poids'},
         name='enfant-percentile-poids'),
    path('enfant/<int:pk>/percentile/taille/', views.PercentileView.as_view(), {'typ': 'taille'},
         name='enfant-percentile-taille'),
    path('enfant/<int:pk>/print/percentile/poids/', views.PercentilePoidsPDFView.as_view(),
         name='print-percentile-poids'),
    path('enfant/<int:pk>/print/percentile/taille/', views.PercentileTaillePDFView.as_view(),
         name='print-percentile-taille'),
    path('enfant/<int:pk>/percentile/email/', views.PercentileByEmailView.as_view(),
         name='enfant-percentile-email'),
    path('enfant/<int:pk>/archiver/', archive_views.ArchiveCreateView.as_view(default_unite="cipe"),
         name='enfant-archiver'),
    path('archive/<int:pk>/desarchiver/', archive_views.ArchiveCIPEDecryptView.as_view(),
         name='enfant-desarchiver'),

    # Thèmes de santé
    path('themesante/list/', views.ThemeSanteListView.as_view(), name='themesante-list'),
    path('themesante/add/', views.ThemeSanteEditView.as_view(is_create=True), name='themesante-add'),
    path('themesante/<int:pk>/edit/', views.ThemeSanteEditView.as_view(), name='themesante-edit'),
    path('themedoc/list/', views.ThemeDocListView.as_view(), name='themedoc-list'),
    path('themedoc/add/', views.ThemeDocEditView.as_view(is_create=True), name='themedoc-add'),
    path('themedoc/<int:pk>/edit/', views.ThemeDocEditView.as_view(), name='themedoc-edit'),
    path('themedoc/<int:pk>/delete/', views.ThemeDocDeleteView.as_view(), name='themedoc-delete'),

    path('documents/', views.GeneralDocListView.as_view(), name='generaldoc-list'),
    path('documents/add/', views.GeneralDocEditView.as_view(is_create=True), name='generaldoc-add'),
    path('documents/<int:pk>/edit/', views.GeneralDocEditView.as_view(), name='generaldoc-edit'),
    path('documents/<int:pk>/delete/', views.GeneralDocDeleteView.as_view(), name='generaldoc-delete'),
    path('documents/categ/<int:pk>/edit/', views.GeneralDocCategEditView.as_view(), name='generaldoccateg-edit'),

    # Stats
    path('statistiques/familles/', views_stats.StatistiquesFamillesView.as_view(), name='stats-familles'),
    path('statistiques/interv/', views_stats.StatistiquesParIntervView.as_view(), name='stats-interv'),
    path('statistiques/localites/', views_stats.StatistiquesLocalitesView.as_view(), name='stats-localites'),
    path('statistiques/lieux/', views_stats.StatistiquesLieuxView.as_view(), name='stats-lieux'),
    path('statistiques/type/', views_stats.StatistiquesTypeView.as_view(), name='stats-type'),
    path('statistiques/nouvelles/', views_stats.StatistiquesNouvellesView.as_view(), name='stats-nouvelles'),
    path('statistiques/themes/', views_stats.StatistiquesThemesView.as_view(), name='stats-themes'),
    path('statistiques/nationalite/', views_stats.StatistiquesNationaliteView.as_view(),
         name='stats-nationalite'),
    path('statistiques/duree/', views_stats.StatistiquesDureeView.as_view(), name='stats-duree'),
    path('statistiques/gen/', views_stats.StatistiquesGenView.as_view(), name='stats-gen'),
    path('statistiques/export/', views_stats.StatistiquesExportView.as_view(), name='stats-export'),
    path('statistiques/export/santene/', views_stats.StatistiquesSanteNEView.as_view(),
         name='stats-export-santene'),
    path('statistiques/export/ascpe/', views_stats.StatistiquesASCPEView.as_view(), name='stats-export-ascpe'),
]

cipe/templates/cipe/base_cipe.html
{% extends "base.html" %}

{% block extrastyle %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/cipe.css' %}">
{% endblock %}

{% block extra_javascript %}
    <script src="{% static 'js/cipe.js' %}"></script>
{% endblock %}

{% block title %}CIPE{% endblock %}

{% block top-navigation %}
<nav id="menu_crne" class="navbar navbar-expand-lg mx-0 mb-1 navbar-light bg-light">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a href="{% url 'home' %}" class="btn btn-sm btn-outline-secondary" role="button">Accueil</a>
            </li>
            {% include 'cipe/menu_principal.html' %}
        </ul>
    </div>
</nav>

<section class="container-fluid">
    <div class="row">
        <div class="col text-end pr-3 pt-2">
            {% block boutons_droite %}{% endblock %}
        </div>
    </div>
</section>
{% endblock %}

cipe/templates/cipe/enfant_perinatal.html
{% extends "cipe/base_cipe.html" %}

{% block extrastyle %}
{{ block.super }}
<link rel="stylesheet" type="text/css" href="{% static 'css/autocomplete.min.css' %}">
<style>
  textarea { height: 2.5em; width: 100%; }
  .narrower label { display: block; }
  .narrower input { max-width: 5em; }
  #id_age_gest_0, #id_age_gest_1 { width: 4em; }
  #id_prescripteur, id_pediatre { width: 100%; }
  #allerg_fam:empty { font-style: italic; }
  #allerg_fam:empty::before { content: 'Aucune signalée'; }
</style>
{% endblock %}

{% block extra_javascript %}
<script src="{% static 'js/autocomplete.min.js' %}"></script>
<script>
document.addEventListener("DOMContentLoaded", function() {
    var input = document.getElementById("id_lieu_acc");
    autocomplete({
        input: input,
        debounceWaitMs: 250,
        fetch: function(text, update) {
            text = text.toLowerCase();
            fetch(input.dataset.url + '?q=' + text).then(resp => resp.json()).then(data => {
                update(data);
            });
        },
        onSelect: function(item) {
            input.value = item.label;
        }
    });
});
</script>
{% endblock %}

{% block boutons_droite %}
    {% if famille %}
        {% include './famille_boutons.html' with active='perinatal' %}
    {% endif %}
{% endblock %}

{% block content %}
    <div class="row border-bottom lead mt-3 mb-3">
        <div class="col">
            Famille {{ famille.nom }} - {{ famille.adresse }} -
            <span class="enfant">{{ object.personne }}
                ({% if object.personne.date_naissance is None %}<span class="missing_field">date de naissance manquante</span>{% else %}{{ object.personne.age_str }}{{ object|age_premat }}{% endif %})
            </span>
        </div>
    </div>

    <form action= "." method="post">{% csrf_token %}
        <div class="row pb-3 mb-3">
            <div class="col-md-8">
               {{ form.motif_demande.label_tag }}{{ form.motif_demande.errors }}{{ form.motif_demande }}
            </div>
            <div class="col-md-4">
                <div class="mb-3">{{ form.prescripteur.label_tag }}{{ form.prescripteur.errors }}{{ form.prescripteur }}</div>
                <div>{{ form.pediatre.label_tag }}{{ form.pediatre.errors }}{{ form.pediatre }}</div>
            </div>
        </div>
        <div class="row mb-3">
            <div class="col-md-6">
                {{ form.lieu_acc.label_tag }}{{ form.lieu_acc.errors }}{{ form.lieu_acc }}
            </div>
            <div class="col-md-3 narrower">
                {{ form.poids_naiss.label_tag }}{{ form.poids_naiss.errors }}{{ form.poids_naiss }}
            </div>
            <div class="col-md-3 narrower">
                {{ form.poids_sortie.label_tag }}{{ form.poids_sortie.errors }}{{ form.poids_sortie }}
            </div>
        </div>
        <div class="row mb-3">
            <div class="col-md-9">
                {{ form.accouchement.label_tag }}{{ form.accouchement.errors }}{{ form.accouchement }}
            </div>
            <div class="col-md-3 narrower">
                {{ form.taille.label_tag }}{{ form.taille.errors }}{{ form.taille }}
            </div>
        </div>
        <div class="row mb-3">
            <div class="col-md-6">
                {{ form.particularites.label_tag }}{{ form.particularites.errors }}{{ form.particularites }}
            </div>
            <div class="col-md-3 narrower">
                {{ form.gestite.label_tag }}{{ form.gestite.errors }}{{ form.gestite }}
            </div>
            <div class="col-md-3 narrower">
                {{ form.parite.label_tag }}{{ form.parite.errors }}{{ form.parite }}
            </div>
        </div>
        <div class="row mb-3">
            <div class="col-md-2">
                <label>Date de naissance :</label><br> {{ form.instance.personne.date_naissance }}<br>
            </div>
            <div class="col-md-3">
                <label>{{ form.age_gest.label_tag }}</label>{{ form.age_gest }}{{ form.age_gest.errors }}
            </div>
            <div class="col-md-1"></div>
            <div class="col-md-2">
                <label>Naissance multiple :</label><br> {{ form.instance.naissance_mult }}
            </div>
        </div>
        <div class="row mb-3">
            <div class="col-md-6">
                {{ form.allaitement.label_tag }}{{ form.allaitement.errors }}{{ form.allaitement }}
            </div>
            <div class="col-md-6">
                {{ form.lait_subst.label_tag }}{{ form.lait_subst.errors }}{{ form.lait_subst }}
            </div>
        </div>
        <div class="row mb-3">
            <div class="col-md-12">
                {{ form.traitement.label_tag }}{{ form.traitement.errors }}{{ form.traitement }}
            </div>
        </div>
        <div class="row mb-3">
            <div class="col-md-6">
                <label>Allergies familiales:</label><br>
                <div id="allerg_fam">{% spaceless %}
                {% for membre in famille.membres.all %}
                    {% if membre.allergies %}<div><i>{{ membre.role.nom }} :</i> {{ membre.allergies }}</div>{% endif %}
                {% endfor %}
                {% endspaceless %}</div>
            </div>
            <div class="col-md-6">
                {{ form.allergies.label_tag }}{{ form.allergies.errors }}{{ form.allergies }}
            </div>
        </div>
    </div>
</div>

        {% if can_edit %}
        <div class="row justify-content-center">
            <div class="col-10">
                {% include "actions.html" %}
            </div>
        </div>
        {% endif %}
    </form>
{% endblock %}

cipe/templates/cipe/famille_boutons.html
<div id="cipe_buttons">
<a class="btn btn-outline-primary btn-sm {% if active == 'coordonnees' %} active {% endif %}" href="{% url 'cipe:famille-edit' famille.pk %}">Infos famille</a>
{% if enfant %}
<a class="btn btn-outline-primary btn-sm {% if active == 'coordonnees' %}active{% endif %}" href="{% url 'personne-edit' famille.pk enfant.pk %}">Infos enfant</a>
<a class="btn btn-outline-primary btn-sm {% if active == 'perinatal' %}active{% endif %}" href="{% url 'cipe:enfant-perinatal' famille.pk enfant.pk %}">Dossier</a>
<a class="btn btn-outline-primary btn-sm {% if active == 'psycho' %}active{% endif %}" href="{% url 'cipe:enfant-psycho' famille.pk enfant.pk %}">Psychom.</a>
<a class="btn btn-outline-primary btn-sm {% if active == 'prestation' %}active{% endif %}" href="{% url 'cipe:prestation-enfant-list' famille.pk enfant.pk %}">Journal</a>
<form class="d-inline" method="post" action="{% url 'cipe:enfant-archiver' enfant.pk %}">
    {% csrf_token %}
    <button type="submit" class="btn btn-sm btn-danger confirm" data-confirm="Voulez-vous vraiment archiver cet enfant ?">
        Archiver
    </button>
</form>
{% elif perms.croixrouge.change_utilisateur %}
    <a class="btn btn-outline-primary btn-sm{% if active == 'acces' %} active{% endif %}" href="{% url 'famille-journalacces' famille.pk %}">Journal d’accès</a>
{% endif %}
</div>

cipe/templates/cipe/famille_list.html
{% extends "cipe/base_cipe.html" %}
{% load cipe_tags %}

{% block extra_javascript %}
<script>
    $(document).ready(function() {
        $("#id_region").change(function() { this.form.submit(); });
    });
</script>
{% endblock %}

{% block above-content %}
<form method="get" class="container-fluid mb-5" action=".">
<div class="row justify-content-center">
    <div class="col-10 famille-filter border">
        <div class="row justify-content-between">
            <div class="col-xl-5 d-flex flex-wrap">
                <div class="select-container">
                    {{ form.famille }}
                </div>
                <div class="select-container">
                    {{ form.adresse }}
                </div>
                <div class="select-container">
                    {{ form.tel }}
                </div>
                <div class="select-container">
                    {{ form.pediatre }}
                </div>
                <div class="select-container">
                    {{ form.region.label_tag }} {{ form.region }}
                </div>
            </div>
            <div class="col-xl-5">
                <div class="select-container">
                    <label for="id_age_de">Âge de</label> {{ form.age_de }} mois <label for="id_age_de">à</label> {{ form.age_a }} mois
                </div>
                <div class="select-container">
                    <label for="id_consult_de">Dernière consultation du</label> {{ form.consult_de }} <label for="id_consult_a">au</label> {{ form.consult_a }}
                </div>
                <div class="select-container">
                    {{ form.besoins_part }} {{ form.besoins_part.label_tag|strip_colon }}
                </div>
                <div class="select-container mt-1">
                    {{ form.a_contacter }}
                </div>
            </div>
            <div class="col-xl-1 text-end">
                <button id="search-button" type="submit" title="Rechercher"><img src="{% static 'admin/img/search.svg' %}"></button>
                <button id="reset-button" type="reset" title="Réinitialiser tous les filtres"><img src="{% static 'img/filter_off.svg' %}"></button>
            </div>
        </div>
    </div>

</div>
</form>
{% endblock %}

{% block content %}
    <div class="row border-bottom mb-3">
        <div class="col"><p class="lead">{{ title }}</p></div>
        {% if not archives %}
        <div class="col text-end">
            <a class="btn btn-sm btn-outline-primary" href="{% url 'cipe:famille-add' %}">Nouvelle famille</a>
        </div>
        {% endif %}
    </div>
    <div class="row">
        <div class="col">
            <table id="benef_table" class="table table-sm table-hover sortable">
                <thead class="table-light">
                    <tr>
                        <th>Nom</th>
                        <th>Adresse</th>
                        <th>Centre</th>
                        <th>Enfants suivis</th>
                    </tr>
                </thead>
                <tbody>
                    {% for famille in object_list %}
                        <tr>
                            <td>
                                <div>
                                    <a href="{% url 'cipe:famille-edit' famille.pk %}" title="Coordonnées">{{ famille.nom }}</a>
                                    {% if famille.besoins_part %}<img class="icon-ui" src="{% static 'img/warning.svg' %}" title="Famille à besoins particuliers" data-bs-toggle="tooltip">{% endif %}
                                </div></td>
                            <td>{{ famille.npa }} {{ famille.localite }}</td>
                            <td>{{ famille.region|default_if_none:'-' }}</td>
                            <td>
                                {% for pers in famille.enfants %}
                                    <a href="{% url 'cipe:prestation-enfant-list' pers.famille_id pers.pk %}" title="Dernière prestation le {{ pers.derniere_prest|default:'-' }}">{{ pers }}</a>, {{ pers.age_str }}{{ pers.suivienfant|age_premat }}
                                    {% with pers|alerte_consult as alerte %}{% if alerte %}
                                    <img class="icon-ui" src="{% static 'img/warning.svg' %}" title="{{ alerte }}" data-bs-toggle="tooltip">
                                    {% endif %}{% endwith %}
                                    {% if not forloop.last %}–{% endif %}
                                {% endfor %}
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

{% block pagination %}
    {{ block.super }}
    <div class="col text-end">
        <a href=".?{% param_replace %}&export=1" title="Exportation de la liste des familles">
            <img class="icon" src="{% static 'ficons/xlsx.svg' %}">
        </a>
    </div>
{% endblock %}

cipe/templates/cipe/partial_psycho_form.html
<form method="post" action="{{ request.path }}">{% csrf_token %}
    {{ form.item }}
    <div>{{ form.acquisition.errors }}{{ form.acquisition }}</div>
    <div>{{ form.remarque.errors }}{{ form.remarque.label_tag }}{{ form.remarque }}</div>
    <button type="submit" class="btn btn-success">Enregistrer</button>
    <button type="button" class="btn btn-secondary cancel">Annuler</button>
</form>

cipe/templates/cipe/partial_psycho_line.html
<tr>
    <td>
        <div>{{ item.item.descriptif }}</div>
        <div class="form-container"></div>
    </td>
    <td class="{{ item.acquisition }}">{{ item.get_acquisition_display }}</td>
    <td>{{ item.date|date:"d.m.Y" }}</td>
    <td>{{ item.remarque }}</td>
    <td>{% if item|can_edit:user %}
        <a href="{% url 'cipe:item-psychoedit' famille.pk item.pk %}" class="btn evaluer">
            <img src="{% static 'img/edit.svg' %}" class="icon-ui" alt="édition">
        </a>
        {% endif %}
    </td>
</tr>

cipe/templates/cipe/stats-duree.html
{% extends "cipe/base_cipe.html" %}

{% block title %}Statistiques{% endblock %}

{% block content %}
    {% include "statistiques/stat-form.html" %}
    {% include "cipe/stat-tabs.html" with active="duree" %}

    <div class="row">
        <div class="col">
            <table class="table table-sm table-hover stat_table">
                <thead>
                    <tr><th></th>{% for month in months %}<th>{{ month }}</th>{% endfor %}<th>Total</th></tr>
                </thead>
                <tbody>
                    <tr><td colspan="{{ months|length|add:2 }}" class="app_line">
                        <p class="lead">Durée des consultations</p></td>
                    </tr>
                    {% for typ, typstats in stats.items %}
                        <tr><td colspan="{{ months|length|add:2 }}" class="app_line">
                            <p class="lead"><i>{{ labels|get_item:typ }}</i></p></td>
                        </tr>
                        {% for duree, data in typstats.items %}
                        <tr>
                            <td>{{ duree }}</td>
                            {% for month in months %}
                                <td class="num">{{ data|get_item:month|default_if_none:0 }}</td>
                            {% endfor %}
                            <td class="num">{{ data.total }}</td>
                        </tr>
                        {% endfor %}
                    {% endfor %}
                </tbody>
            </table>
            <div class="text-end">
                <a href=".?{% param_replace %}&export=1"><img class="icon-ui" src="{% static 'ficons/xlsx.svg' %}"></a>
            </div>
        </div>
    </div>
{% endblock %}

cipe/templates/cipe/stats-export.html
{% extends "cipe/base_cipe.html" %}

{% block title %}Statistiques{% endblock %}

{% block content %}
    {% include "statistiques/stat-form.html" %}
    {% include "cipe/stat-tabs.html" with active="export" %}

    <div class="row">
        <div class="col">
            <p class="app_line lead">Exportations de statistiques</p>
            <div>
                <form method="post" action="{% url 'cipe:stats-export-ascpe' %}">{% csrf_token %}
                <fieldset>
                    <b>Données statistiques annuelles pour l’ASCPE</b><br>
                    {{ form.year }}
                    <button type="submit"><img class="icon-ui" src="{% static 'ficons/xlsx.svg' %}"> Exporter</button>
                </fieldset>
                </form>
            </div>
            <div class="mt-3">
                <form method="post" action="{% url 'cipe:stats-export-santene' %}">{% csrf_token %}
                <fieldset>
                    <b>Données statistiques pour la Santé publique</b><br>
                    {{ form.year }}
                    <button type="submit"><img class="icon-ui" src="{% static 'ficons/xlsx.svg' %}"> Exporter</button>
                </fieldset>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

cipe/templates/cipe/suivis_archives_list.html
{% extends "cipe/base_cipe.html" %}

{% block above-content %}
<form method="get" class="container-fluid mb-5" action=".">
<div class="row justify-content-center">
    <div class="col-10 famille-filter border">
        <div class="row justify-content-between">
            <div class="col-xl-9 d-flex flex-wrap">
                <div class="select-container">
                    {{ form.nom }}
                </div>
                <div class="select-container">
                    {{ form.localite }}
                </div>
                <div class="select-container">
                    {{ form.region.label_tag }} {{ form.region }}
                </div>
            </div>
            <div class="col-xl-1 text-end">
                <button id="search-button" type="submit" title="Rechercher"><img src="{% static 'admin/img/search.svg' %}"></button>
                <button id="reset-button" type="reset" title="Réinitialiser tous les filtres"><img src="{% static 'img/filter_off.svg' %}"></button>
            </div>
        </div>
    </div>

</div>
</form>
{% endblock %}

{% block content %}
    <div class="row border-bottom mb-3">
        <div class="col"><p class="lead">{{ title }}</p></div>
    </div>
    <div class="row">
        <div class="col">
            <table id="benef_table" class="table table-sm table-hover sortable">
                <thead class="table-light">
                    <tr>
                        <th>Nom / prénom</th>
                        <th>Localité</th>
                        <th>Centre</th>
                    </tr>
                </thead>
                <tbody>
                    {% for archive in object_list %}
                        <tr>
                            <td>
                                <a href="{% url 'cipe:enfant-desarchiver' archive.pk %}" title="Désarchiver">
                                    {{ archive.nom }} {{ archive.prenom }}
                                </a>
                            </td>
                            <td>{{ archive.npa }} {{ archive.localite }}</td>
                            <td>{{ archive.region|default:'-' }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}